### ISSUE TITLE
Initializer for will_paginate crashes when active_record is not loaded

### ISSUE THREAD

**Issue by redgetan** [rubysherpas/forem#183]
## Problem

The initializer for will_paginate 

``` ruby
if defined?(WillPaginate)
  module WillPaginate
    module ActiveRecord
      module RelationMethods
        alias_method :per, :per_page
        alias_method :num_pages, :total_pages
      end
    end
  end
end
```

would not run properly if active_record is not loaded. It would crash saying 'alias_method': undefined method `per_page' for module`WillPaginate::ActiveRecord::RelationMethods' (NameError). Apparently it's trying to find per_page method in a module defined under (https://github.com/mislav/will_paginate/blob/master/lib/will_paginate/active_record.rb#L18-30) which won't be required until active_record is loaded (https://github.com/mislav/will_paginate/blob/master/lib/will_paginate/railtie.rb#L9-11). 
## To reproduce the problem
1. I'm using ruby 1.9.3p125 (2012-02-16 revision 34643) [x86_64-darwin11.2.0]
2. rails new sample_proj
3. Add these to your Gemfile

``` ruby
gem 'forem', :git => "git://github.com/radar/forem.git"
gem 'will_paginate', '~> 3.0'
```
1. `bundle install`
2. `rails generate model User name email` or simply `rails g`

```
/Users/reg/.rvm/gems/ruby-1.9.3-p125/bundler/gems/forem-233cac409e6b/config/initializers/will_paginate.rb:5:in `alias_method': undefined method `per_page' for module `WillPaginate::ActiveRecord::RelationMethods' (NameError)
    from /Users/reg/.rvm/gems/ruby-1.9.3-p125/bundler/gems/forem-233cac409e6b/config/initializers/will_paginate.rb:5:in `<module:RelationMethods>'
    from /Users/reg/.rvm/gems/ruby-1.9.3-p125/bundler/gems/forem-233cac409e6b/config/initializers/will_paginate.rb:4:in `<module:ActiveRecord>'
    from /Users/reg/.rvm/gems/ruby-1.9.3-p125/bundler/gems/forem-233cac409e6b/config/initializers/will_paginate.rb:3:in `<module:WillPaginate>'
    from /Users/reg/.rvm/gems/ruby-1.9.3-p125/bundler/gems/forem-233cac409e6b/config/initializers/will_paginate.rb:2:in `<top (required)>'
    from /Users/reg/.rvm/gems/ruby-1.9.3-p125/gems/activesupport-3.2.2/lib/active_support/dependencies.rb:245:in `load'
    from /Users/reg/.rvm/gems/ruby-1.9.3-p125/gems/activesupport-3.2.2/lib/active_support/dependencies.rb:245:in `block in load'
    from /Users/reg/.rvm/gems/ruby-1.9.3-p125/gems/activesupport-3.2.2/lib/active_support/dependencies.rb:236:in `load_dependency'
    from /Users/reg/.rvm/gems/ruby-1.9.3-p125/gems/activesupport-3.2.2/lib/active_support/dependencies.rb:245:in `load'
    from /Users/reg/.rvm/gems/ruby-1.9.3-p125/gems/railties-3.2.2/lib/rails/engine.rb:588:in `block (2 levels) in <class:Engine>'
    from /Users/reg/.rvm/gems/ruby-1.9.3-p125/gems/railties-3.2.2/lib/rails/engine.rb:587:in `each'
    from /Users/reg/.rvm/gems/ruby-1.9.3-p125/gems/railties-3.2.2/lib/rails/engine.rb:587:in `block in <class:Engine>'
    from /Users/reg/.rvm/gems/ruby-1.9.3-p125/gems/railties-3.2.2/lib/rails/initializable.rb:30:in `instance_exec'
    from /Users/reg/.rvm/gems/ruby-1.9.3-p125/gems/railties-3.2.2/lib/rails/initializable.rb:30:in `run'
    from /Users/reg/.rvm/gems/ruby-1.9.3-p125/gems/railties-3.2.2/lib/rails/initializable.rb:55:in `block in run_initializers'
    from /Users/reg/.rvm/gems/ruby-1.9.3-p125/gems/railties-3.2.2/lib/rails/initializable.rb:54:in `each'
    from /Users/reg/.rvm/gems/ruby-1.9.3-p125/gems/railties-3.2.2/lib/rails/initializable.rb:54:in `run_initializers'
    from /Users/reg/.rvm/gems/ruby-1.9.3-p125/gems/railties-3.2.2/lib/rails/application.rb:136:in `initialize!'
    from /Users/reg/.rvm/gems/ruby-1.9.3-p125/gems/railties-3.2.2/lib/rails/railtie/configurable.rb:30:in `method_missing'
    from /Users/reg/ruby/rails/crash_rep/config/environment.rb:5:in `<top (required)>'
    from /Users/reg/.rvm/gems/ruby-1.9.3-p125/gems/railties-3.2.2/lib/rails/application.rb:103:in `require'
    from /Users/reg/.rvm/gems/ruby-1.9.3-p125/gems/railties-3.2.2/lib/rails/application.rb:103:in `require_environment!'
    from /Users/reg/.rvm/gems/ruby-1.9.3-p125/gems/railties-3.2.2/lib/rails/commands.rb:25:in `<top (required)>'
    from script/rails:6:in `require'
    from script/rails:6:in `<main>'
```
## Proposed solutions?

A friend of mine recommended that to wrap the module extension in an ActiveSupport on_load :active_record block. Is this a clean solution?

``` ruby
if defined?(WillPaginate)
  ActiveSupport.on_load :active_record do
    module WillPaginate
      module ActiveRecord
        module RelationMethods
          alias_method :per, :per_page
          alias_method :num_pages, :total_pages
        end
      end
    end
  end
end
```

**Comment by parndt** [comment]
Solution seems good to me. @radar ? @knewter you agree?

**Comment by ericraio** [comment]
I am current dealing with this issue in my project right now. :(

**Comment by redgetan** [comment]
Sorry, my statement was a bit inaccurate, it does not depend on loading of active_record, but rather ActiveRecord::Base.

**Comment by radar** [comment]
I like this fix. Please submit a patch and we'll merge it!

**Comment by nebiros** [comment]
I also have the same issue, I just add `gem "forem", :git => "git://github.com/radar/forem.git"` to my Gemfile (http://pastie.org/private/hhxbkn4pagwdbfoeeu5rw), and I got the same error: 

```
/Users/nebiros/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/bundler/gems/forem-fe18d8d320b7/config/initializers/will_paginate.rb:6:in `alias_method': undefined method `per_page' for module `WillPaginate::ActiveRecord::RelationMethods' (NameError)
```

Here's the error log: http://pastie.org/private/wcrvxm5nrq4cmweixkeyw.
