### ISSUE TITLE
Error while showing forum topic

### ISSUE THREAD

**Issue by bbatsov** [rubysherpas/forem#248]
Hi guys,

I've run into a bit of an issue with forem - when I try to display a topic (say `http://localhost:3000/forums/forums/1/topics/1`) I get the following stack trace ( + some console output):

```
Started GET "/forums/forums/1/topics/1" for 127.0.0.1 at 2012-06-15 15:22:31 +0300
Processing by Forem::TopicsController#show as HTML
  Parameters: {"forum_id"=>"1", "id"=>"1"}
  Forem::Forum Load (0.5ms)  SELECT "forem_forums".* FROM "forem_forums" WHERE "forem_forums"."id" = $1 LIMIT 1  [["id", "1"]]
  User Load (0.7ms)  SELECT "users".* FROM "users" WHERE "users"."id" = 1 LIMIT 1
  Forem::Category Load (0.4ms)  SELECT "forem_categories".* FROM "forem_categories" WHERE "forem_categories"."id" = 1 LIMIT 1
  Forem::Topic Load (0.4ms)  SELECT "forem_topics".* FROM "forem_topics" WHERE "forem_topics"."forum_id" = 1 AND "forem_topics"."id" = $1 LIMIT 1  [["id", "1"]]
  Forem::Forum Load (0.5ms)  SELECT "forem_forums".* FROM "forem_forums" WHERE "forem_forums"."id" = 1 LIMIT 1
  Forem::View Load (0.6ms)  SELECT "forem_views".* FROM "forem_views" WHERE "forem_views"."viewable_id" = 1 AND "forem_views"."viewable_type" = 'Forem::Topic' AND "forem_views"."user_id" = 1 LIMIT 1
   (0.2ms)  BEGIN
   (0.4ms)  UPDATE "forem_views" SET "count" = 3, "updated_at" = '2012-06-15 12:22:31.929042' WHERE "forem_views"."id" = 2
   (1.6ms)  COMMIT
   (0.4ms)  BEGIN
  Forem::Post Load (0.5ms)  SELECT "forem_posts".* FROM "forem_posts" WHERE "forem_posts"."topic_id" = 1 ORDER BY forem_posts.created_at ASC LIMIT 1
  User Load (0.5ms)  SELECT "users".* FROM "users" WHERE "users"."id" = 1 LIMIT 1
   (0.3ms)  UPDATE "forem_topics" SET "views_count" = 3, "updated_at" = '2012-06-15 12:22:31.936473' WHERE "forem_topics"."id" = 1
   (0.3ms)  COMMIT
  Rendered /Users/bozhidar/.rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/bundler/gems/forem-fe18d8d320b7/app/views/forem/topics/_head.html.erb (1.2ms)
  Forem::Subscription Exists (0.5ms)  SELECT 1 FROM "forem_subscriptions" WHERE "forem_subscriptions"."topic_id" = 1 AND "forem_subscriptions"."subscriber_id" = 1 LIMIT 1
  Rendered /Users/bozhidar/.rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/bundler/gems/forem-fe18d8d320b7/app/views/forem/moderation/_options.html.erb (0.9ms)
   (0.6ms)  SELECT COUNT(*) FROM "forem_posts" WHERE "forem_posts"."topic_id" = 1
  Forem::Post Load (0.6ms)  SELECT "forem_posts".* FROM "forem_posts" WHERE "forem_posts"."topic_id" = 1 ORDER BY forem_posts.created_at ASC LIMIT 20 OFFSET 0
  User Load (0.7ms)  SELECT "users".* FROM "users" WHERE "users"."id" = 1 LIMIT 1
  Forem::Topic Load (0.4ms)  SELECT "forem_topics".* FROM "forem_topics" WHERE "forem_topics"."id" = 1 LIMIT 1
  Forem::Forum Load (0.4ms)  SELECT "forem_forums".* FROM "forem_forums" WHERE "forem_forums"."id" = 1 LIMIT 1
  Rendered /Users/bozhidar/.rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/bundler/gems/forem-fe18d8d320b7/app/views/forem/moderation/_options.html.erb (1.6ms)
  Rendered /Users/bozhidar/.rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/bundler/gems/forem-fe18d8d320b7/app/views/forem/posts/_moderation_tools.html.erb (3.9ms)
  Rendered /Users/bozhidar/.rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/bundler/gems/forem-fe18d8d320b7/app/views/forem/posts/_post.html.erb (11.5ms)
  Rendered /Users/bozhidar/.rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/bundler/gems/forem-fe18d8d320b7/app/views/forem/topics/show.html.erb within layouts/application (81.0ms)
Completed 500 Internal Server Error in 108ms

ActionView::Template::Error (undefined method `[]' for nil:NilClass):
    1: <%= fields_for "posts[#{post.id}]" do |f| %>
    2:   <%= render "forem/moderation/options", :f => f %>
    3: <% end %>
    4: <br>
  client_side_validations (3.1.4) lib/client_side_validations/action_view/form_helper.rb:46:in `fields_for'
  /Users/bozhidar/.rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/bundler/gems/forem-fe18d8d320b7/app/views/forem/posts/_moderation_tools.html.erb:1:in `___sers_bozhidar__rbenv_versions_______p____lib_ruby_gems_______bundler_gems_forem_fe__d_d___b__app_views_forem_posts__moderation_tools_html_erb__4391586347607326733_70228525843280'
  actionpack (3.2.3) lib/action_view/template.rb:143:in `block in render'
# more is omitted
```

Nothing seems obviously `nil` to me, but I haven't debugged the problem yet since I decided to first check with you if I'm doing something wrong.

**Comment by radar** [comment]
I believe this is because of your `client_side_validations` extension. The final line of the stacktrace is this one, and therefore I suspect it is the cause. Please investigate.
