### ISSUE TITLE
Undefined Method 'slug' for CreateForemCategories

### ISSUE THREAD

**Issue by ghost** [rubysherpas/forem#270]
I installed Forem successfully yesterday, including running the migration. Today, I dropped my database, recreated it, and then tried to run the migration again. This time I get the error:

```
undefined method 'slug' for #<Forem::Category:0x40cd910>
```

I have not altered Forem or any of its files.

Also worth noting, I have FriendlyID installed and it works well. Also, there is no 'slug' column present in CreateForemCategories. What other information might help?

**Comment by parndt** [comment]
Does this work:

rake railties:install:migrations
rake db:migrate

**Comment by ghost** [comment]
The railties worked:

```
Copied migration 20120726235302_add_friendly_id_slugs.forem.rb
```

As promising as that message looked, I'm still getting the error when I run db:migrate, though.

**Comment by radar** [comment]
Could you provide a stack trace for the error?

**Comment by ghost** [comment]
```
==  CreateForemCategories: migrating ==========================================
-- create_table(:forem_categories)
   -> 0.0800s
rake aborted!
An error has occurred, all later migrations canceled:

undefined method `slug' for #<Forem::Category:0x3887f88>
C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/activemodel-3.2.5/lib/activ
e_model/attribute_methods.rb:407:in `method_missing'
C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/activerecord-3.2.5/lib/acti
ve_record/attribute_methods.rb:149:in `method_missing'
C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/friendly_id-4.0.7/lib/frien
dly_id/slugged.rb:254:in `should_generate_new_friendly_id?'
C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/friendly_id-4.0.7/lib/frien
dly_id/slugged.rb:273:in `set_slug'
C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/activesupport-3.2.5/lib/act
ive_support/callbacks.rb:407:in `_run__267392298__validation__1000058309__callba
cks'
C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/activesupport-3.2.5/lib/act
ive_support/callbacks.rb:405:in `__run_callback'
C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/activesupport-3.2.5/lib/act
ive_support/callbacks.rb:385:in `_run_validation_callbacks'
C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/activesupport-3.2.5/lib/act
ive_support/callbacks.rb:81:in `run_callbacks'
C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/activemodel-3.2.5/lib/activ
e_model/validations/callbacks.rb:53:in `run_validations!'
C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/activemodel-3.2.5/lib/activ
e_model/validations.rb:193:in `valid?'
C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/activerecord-3.2.5/lib/acti
ve_record/validations.rb:69:in `valid?'
C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/activerecord-3.2.5/lib/acti
ve_record/validations.rb:77:in `perform_validations'
C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/activerecord-3.2.5/lib/acti
ve_record/validations.rb:50:in `save'
C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/activerecord-3.2.5/lib/acti
ve_record/attribute_methods/dirty.rb:22:in `save'
C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/activerecord-3.2.5/lib/acti
ve_record/transactions.rb:241:in `block (2 levels) in save'
C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/activerecord-3.2.5/lib/acti
ve_record/transactions.rb:295:in `block in with_transaction_returning_status'
C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/activerecord-3.2.5/lib/acti
ve_record/connection_adapters/abstract/database_statements.rb:192:in `transactio
n'
C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/activerecord-3.2.5/lib/acti
ve_record/transactions.rb:208:in `transaction'
C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/activerecord-3.2.5/lib/acti
ve_record/transactions.rb:293:in `with_transaction_returning_status'
C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/activerecord-3.2.5/lib/acti
ve_record/transactions.rb:241:in `block in save'
C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/activerecord-3.2.5/lib/acti
ve_record/transactions.rb:252:in `rollback_active_record_state!'
C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/activerecord-3.2.5/lib/acti
ve_record/transactions.rb:240:in `save'
C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/activerecord-3.2.5/lib/acti
ve_record/persistence.rb:45:in `create'
C:/Sites/shelflives/db/migrate/20120726003066_create_forem_categories.forem.rb:9
:in `change'
C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/activerecord-3.2.5/lib/acti
ve_record/migration.rb:407:in `block (2 levels) in migrate'
C:/RailsInstaller/Ruby1.9.3/lib/ruby/1.9.1/benchmark.rb:280:in `measure'
C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/activerecord-3.2.5/lib/acti
ve_record/migration.rb:407:in `block in migrate'
C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/activerecord-3.2.5/lib/acti
ve_record/connection_adapters/abstract/connection_pool.rb:123:in `with_connectio
n'
C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/activerecord-3.2.5/lib/acti
ve_record/migration.rb:389:in `migrate'
C:in `migrate'
C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/activerecord-3.2.5/lib/acti
ve_record/migration.rb:720:in `block (2 levels) in migrate'
C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/activerecord-3.2.5/lib/acti
ve_record/migration.rb:777:in `call'
C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/activerecord-3.2.5/lib/acti
ve_record/migration.rb:777:in `ddl_transaction'
C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/activerecord-3.2.5/lib/acti
ve_record/migration.rb:719:in `block in migrate'
C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/activerecord-3.2.5/lib/acti
ve_record/migration.rb:700:in `each'
C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/activerecord-3.2.5/lib/acti
ve_record/migration.rb:700:in `migrate'
C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/activerecord-3.2.5/lib/acti
ve_record/migration.rb:570:in `up'
C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/activerecord-3.2.5/lib/acti
ve_record/migration.rb:551:in `migrate'
C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/activerecord-3.2.5/lib/acti
ve_record/railties/databases.rake:153:in `block (2 levels) in <top (required)>'
C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/task.
rb:205:in `call'
C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/task.
rb:205:in `block in execute'
C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/task.
rb:200:in `each'
C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/task.
rb:200:in `execute'
C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/task.
rb:158:in `block in invoke_with_call_chain'
C:/RailsInstaller/Ruby1.9.3/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/task.
rb:151:in `invoke_with_call_chain'
C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/task.
rb:144:in `invoke'
C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/appli
cation.rb:116:in `invoke_task'
C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/appli
cation.rb:94:in `block (2 levels) in top_level'
C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/appli
cation.rb:94:in `each'
C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/appli
cation.rb:94:in `block in top_level'
C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/appli
cation.rb:133:in `standard_exception_handling'
C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/appli
cation.rb:88:in `top_level'
C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/appli
cation.rb:66:in `block in run'
C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/appli
cation.rb:133:in `standard_exception_handling'
C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/appli
cation.rb:63:in `run'
C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/bin/rake:33:in
 `<top (required)>'
C:/RailsInstaller/Ruby1.9.3/bin/rake:19:in `load'
C:/RailsInstaller/Ruby1.9.3/bin/rake:19:in `<main>'
Tasks: TOP => db:migrate
```

**Comment by parndt** [comment]
Ah we have new migrations but of course existing users would get stung!

Here is the new version of that file:
https://github.com/radar/forem/blob/master/db/migrate/20111103210835_create_forem_categories.rb

If you replace the contents of the one you have under db/migrate/ with
that one I linked your problem should be solved

This is why seeding in migrations is so bad @radar

**Comment by radar** [comment]
Ok, so why is friendly_id getting involved in that model when it shouldn't be? Perhaps @parndt would know.

**Comment by ghost** [comment]
@parndt That did the trick. Thanks!
