### ISSUE TITLE
forem:install generator fails on refinerycms

### ISSUE THREAD

**Issue by eostrom** [rubysherpas/forem#325]
I installed Refinery CMS:

``` sh
gem install refinerycms
refinerycms reforemery
cd reforemery
rails server
```

Fired it up and created the initial user.

Then I installed forem, as per the README, by adding to Gemfile:

``` ruby
gem 'forem', :git => "git://github.com/radar/forem.git"
```

And at the command line:

``` sh
$ rails g forem:install
Copying over Forem migrations...
What is your user class called? [User] Refinery::User
What is the current_user helper called in your app? [current_user] current_refinery_user
Defining forem_user method inside ApplicationController...
      insert  app/controllers/application_controller.rb
Adding forem initializer (config/initializers/forem.rb)...
      create  config/initializers/forem.rb
Running rake db:migrate
Creating default forum and topic
/Users/eostrom/.rvm/gems/ruby-1.9.2-p290@iowl/gems/activemodel-3.2.6/lib/active_model/attribute_methods.rb:407:in `method_missing': undefined method `forem_needs_moderation?' for #<Refinery::User:0x007ff4ea951690> (NoMethodError)
    from /Users/eostrom/.rvm/gems/ruby-1.9.2-p290@iowl/gems/activerecord-3.2.6/lib/active_record/attribute_methods.rb:149:in `method_missing'
    from /Users/eostrom/.rvm/gems/ruby-1.9.2-p290@iowl/gems/activesupport-3.2.6/lib/active_support/core_ext/object/try.rb:36:in `try'
    from /Users/eostrom/.rvm/gems/ruby-1.9.2-p290@iowl/bundler/gems/forem-66e2f512d0f0/app/models/forem/post.rb:116:in `skip_pending_review'
    from /Users/eostrom/.rvm/gems/ruby-1.9.2-p290@iowl/gems/activesupport-3.2.6/lib/active_support/callbacks.rb:417:in `_run__280411519566598945__create__954061338601118689__callbacks'
    from /Users/eostrom/.rvm/gems/ruby-1.9.2-p290@iowl/gems/activesupport-3.2.6/lib/active_support/callbacks.rb:405:in `__run_callback'
    from /Users/eostrom/.rvm/gems/ruby-1.9.2-p290@iowl/gems/activesupport-3.2.6/lib/active_support/callbacks.rb:385:in `_run_create_callbacks'
    from /Users/eostrom/.rvm/gems/ruby-1.9.2-p290@iowl/gems/activesupport-3.2.6/lib/active_support/callbacks.rb:81:in `run_callbacks'
    from /Users/eostrom/.rvm/gems/ruby-1.9.2-p290@iowl/gems/activerecord-3.2.6/lib/active_record/callbacks.rb:268:in `create'
    from /Users/eostrom/.rvm/gems/ruby-1.9.2-p290@iowl/gems/activerecord-3.2.6/lib/active_record/persistence.rb:344:in `create_or_update'
    from /Users/eostrom/.rvm/gems/ruby-1.9.2-p290@iowl/gems/activerecord-3.2.6/lib/active_record/callbacks.rb:264:in `block in create_or_update'
    from /Users/eostrom/.rvm/gems/ruby-1.9.2-p290@iowl/gems/activesupport-3.2.6/lib/active_support/callbacks.rb:447:in `_run__280411519566598945__save__954061338601118689__callbacks'
    from /Users/eostrom/.rvm/gems/ruby-1.9.2-p290@iowl/gems/activesupport-3.2.6/lib/active_support/callbacks.rb:405:in `__run_callback'
    from /Users/eostrom/.rvm/gems/ruby-1.9.2-p290@iowl/gems/activesupport-3.2.6/lib/active_support/callbacks.rb:385:in `_run_save_callbacks'
    from /Users/eostrom/.rvm/gems/ruby-1.9.2-p290@iowl/gems/activesupport-3.2.6/lib/active_support/callbacks.rb:81:in `run_callbacks'
    from /Users/eostrom/.rvm/gems/ruby-1.9.2-p290@iowl/gems/activerecord-3.2.6/lib/active_record/callbacks.rb:264:in `create_or_update'
    from /Users/eostrom/.rvm/gems/ruby-1.9.2-p290@iowl/gems/activerecord-3.2.6/lib/active_record/persistence.rb:84:in `save'
    from /Users/eostrom/.rvm/gems/ruby-1.9.2-p290@iowl/gems/activerecord-3.2.6/lib/active_record/validations.rb:50:in `save'
    from /Users/eostrom/.rvm/gems/ruby-1.9.2-p290@iowl/gems/activerecord-3.2.6/lib/active_record/attribute_methods/dirty.rb:22:in `save'
    from /Users/eostrom/.rvm/gems/ruby-1.9.2-p290@iowl/gems/activerecord-3.2.6/lib/active_record/transactions.rb:241:in `block (2 levels) in save'
    from /Users/eostrom/.rvm/gems/ruby-1.9.2-p290@iowl/gems/activerecord-3.2.6/lib/active_record/transactions.rb:295:in `block in with_transaction_returning_status'
    from /Users/eostrom/.rvm/gems/ruby-1.9.2-p290@iowl/gems/activerecord-3.2.6/lib/active_record/connection_adapters/abstract/database_statements.rb:192:in `transaction'
    from /Users/eostrom/.rvm/gems/ruby-1.9.2-p290@iowl/gems/activerecord-3.2.6/lib/active_record/transactions.rb:208:in `transaction'
    from /Users/eostrom/.rvm/gems/ruby-1.9.2-p290@iowl/gems/activerecord-3.2.6/lib/active_record/transactions.rb:293:in `with_transaction_returning_status'
    from /Users/eostrom/.rvm/gems/ruby-1.9.2-p290@iowl/gems/activerecord-3.2.6/lib/active_record/transactions.rb:241:in `block in save'
    from /Users/eostrom/.rvm/gems/ruby-1.9.2-p290@iowl/gems/activerecord-3.2.6/lib/active_record/transactions.rb:252:in `rollback_active_record_state!'
    from /Users/eostrom/.rvm/gems/ruby-1.9.2-p290@iowl/gems/activerecord-3.2.6/lib/active_record/transactions.rb:240:in `save'
    from /Users/eostrom/.rvm/gems/ruby-1.9.2-p290@iowl/gems/activerecord-3.2.6/lib/active_record/associations/has_many_association.rb:16:in `insert_record'
    from /Users/eostrom/.rvm/gems/ruby-1.9.2-p290@iowl/gems/activerecord-3.2.6/lib/active_record/autosave_association.rb:344:in `block in save_collection_association'
    from /Users/eostrom/.rvm/gems/ruby-1.9.2-p290@iowl/gems/activerecord-3.2.6/lib/active_record/autosave_association.rb:335:in `each'
    from /Users/eostrom/.rvm/gems/ruby-1.9.2-p290@iowl/gems/activerecord-3.2.6/lib/active_record/autosave_association.rb:335:in `save_collection_association'
    from /Users/eostrom/.rvm/gems/ruby-1.9.2-p290@iowl/gems/activerecord-3.2.6/lib/active_record/autosave_association.rb:191:in `block in add_autosave_association_callbacks'
    from /Users/eostrom/.rvm/gems/ruby-1.9.2-p290@iowl/gems/activerecord-3.2.6/lib/active_record/autosave_association.rb:161:in `instance_eval'
    from /Users/eostrom/.rvm/gems/ruby-1.9.2-p290@iowl/gems/activerecord-3.2.6/lib/active_record/autosave_association.rb:161:in `block in define_non_cyclic_method'
    from /Users/eostrom/.rvm/gems/ruby-1.9.2-p290@iowl/gems/activesupport-3.2.6/lib/active_support/callbacks.rb:413:in `_run__264134804237592305__create__954061338601118689__callbacks'
    from /Users/eostrom/.rvm/gems/ruby-1.9.2-p290@iowl/gems/activesupport-3.2.6/lib/active_support/callbacks.rb:405:in `__run_callback'
    from /Users/eostrom/.rvm/gems/ruby-1.9.2-p290@iowl/gems/activesupport-3.2.6/lib/active_support/callbacks.rb:385:in `_run_create_callbacks'
    from /Users/eostrom/.rvm/gems/ruby-1.9.2-p290@iowl/gems/activesupport-3.2.6/lib/active_support/callbacks.rb:81:in `run_callbacks'
    from /Users/eostrom/.rvm/gems/ruby-1.9.2-p290@iowl/gems/activerecord-3.2.6/lib/active_record/callbacks.rb:268:in `create'
    from /Users/eostrom/.rvm/gems/ruby-1.9.2-p290@iowl/gems/activerecord-3.2.6/lib/active_record/persistence.rb:344:in `create_or_update'
    from /Users/eostrom/.rvm/gems/ruby-1.9.2-p290@iowl/gems/activerecord-3.2.6/lib/active_record/callbacks.rb:264:in `block in create_or_update'
    from /Users/eostrom/.rvm/gems/ruby-1.9.2-p290@iowl/gems/activesupport-3.2.6/lib/active_support/callbacks.rb:458:in `_run__264134804237592305__save__954061338601118689__callbacks'
    from /Users/eostrom/.rvm/gems/ruby-1.9.2-p290@iowl/gems/activesupport-3.2.6/lib/active_support/callbacks.rb:405:in `__run_callback'
    from /Users/eostrom/.rvm/gems/ruby-1.9.2-p290@iowl/gems/activesupport-3.2.6/lib/active_support/callbacks.rb:385:in `_run_save_callbacks'
    from /Users/eostrom/.rvm/gems/ruby-1.9.2-p290@iowl/gems/activesupport-3.2.6/lib/active_support/callbacks.rb:81:in `run_callbacks'
    from /Users/eostrom/.rvm/gems/ruby-1.9.2-p290@iowl/gems/activerecord-3.2.6/lib/active_record/callbacks.rb:264:in `create_or_update'
    from /Users/eostrom/.rvm/gems/ruby-1.9.2-p290@iowl/gems/activerecord-3.2.6/lib/active_record/persistence.rb:104:in `save!'
    from /Users/eostrom/.rvm/gems/ruby-1.9.2-p290@iowl/gems/activerecord-3.2.6/lib/active_record/validations.rb:56:in `save!'
    from /Users/eostrom/.rvm/gems/ruby-1.9.2-p290@iowl/gems/activerecord-3.2.6/lib/active_record/attribute_methods/dirty.rb:33:in `save!'
    from /Users/eostrom/.rvm/gems/ruby-1.9.2-p290@iowl/gems/activerecord-3.2.6/lib/active_record/transactions.rb:246:in `block in save!'
    from /Users/eostrom/.rvm/gems/ruby-1.9.2-p290@iowl/gems/activerecord-3.2.6/lib/active_record/transactions.rb:295:in `block in with_transaction_returning_status'
    from /Users/eostrom/.rvm/gems/ruby-1.9.2-p290@iowl/gems/activerecord-3.2.6/lib/active_record/connection_adapters/abstract/database_statements.rb:192:in `transaction'
    from /Users/eostrom/.rvm/gems/ruby-1.9.2-p290@iowl/gems/activerecord-3.2.6/lib/active_record/transactions.rb:208:in `transaction'
    from /Users/eostrom/.rvm/gems/ruby-1.9.2-p290@iowl/gems/activerecord-3.2.6/lib/active_record/transactions.rb:293:in `with_transaction_returning_status'
    from /Users/eostrom/.rvm/gems/ruby-1.9.2-p290@iowl/gems/activerecord-3.2.6/lib/active_record/transactions.rb:246:in `save!'
    from /Users/eostrom/.rvm/gems/ruby-1.9.2-p290@iowl/bundler/gems/forem-66e2f512d0f0/db/seeds.rb:17:in `<top (required)>'
    from /Users/eostrom/.rvm/gems/ruby-1.9.2-p290@iowl/gems/activesupport-3.2.6/lib/active_support/dependencies.rb:245:in `load'
    from /Users/eostrom/.rvm/gems/ruby-1.9.2-p290@iowl/gems/activesupport-3.2.6/lib/active_support/dependencies.rb:245:in `block in load'
    from /Users/eostrom/.rvm/gems/ruby-1.9.2-p290@iowl/gems/activesupport-3.2.6/lib/active_support/dependencies.rb:236:in `load_dependency'
    from /Users/eostrom/.rvm/gems/ruby-1.9.2-p290@iowl/gems/activesupport-3.2.6/lib/active_support/dependencies.rb:245:in `load'
    from /Users/eostrom/.rvm/gems/ruby-1.9.2-p290@iowl/gems/railties-3.2.6/lib/rails/engine.rb:520:in `load_seed'
    from /Users/eostrom/.rvm/gems/ruby-1.9.2-p290@iowl/gems/railties-3.2.6/lib/rails/railtie/configurable.rb:30:in `method_missing'
    from /Users/eostrom/.rvm/gems/ruby-1.9.2-p290@iowl/bundler/gems/forem-66e2f512d0f0/lib/generators/forem/install_generator.rb:67:in `seed_database'
    from /Users/eostrom/.rvm/gems/ruby-1.9.2-p290@iowl/gems/thor-0.16.0/lib/thor/task.rb:27:in `run'
    from /Users/eostrom/.rvm/gems/ruby-1.9.2-p290@iowl/gems/thor-0.16.0/lib/thor/invocation.rb:120:in `invoke_task'
    from /Users/eostrom/.rvm/gems/ruby-1.9.2-p290@iowl/gems/thor-0.16.0/lib/thor/invocation.rb:126:in `block in invoke_all'
    from /Users/eostrom/.rvm/gems/ruby-1.9.2-p290@iowl/gems/thor-0.16.0/lib/thor/invocation.rb:126:in `each'
    from /Users/eostrom/.rvm/gems/ruby-1.9.2-p290@iowl/gems/thor-0.16.0/lib/thor/invocation.rb:126:in `map'
    from /Users/eostrom/.rvm/gems/ruby-1.9.2-p290@iowl/gems/thor-0.16.0/lib/thor/invocation.rb:126:in `invoke_all'
    from /Users/eostrom/.rvm/gems/ruby-1.9.2-p290@iowl/gems/thor-0.16.0/lib/thor/group.rb:238:in `dispatch'
    from /Users/eostrom/.rvm/gems/ruby-1.9.2-p290@iowl/gems/thor-0.16.0/lib/thor/base.rb:425:in `start'
    from /Users/eostrom/.rvm/gems/ruby-1.9.2-p290@iowl/gems/railties-3.2.6/lib/rails/generators.rb:171:in `invoke'
    from /Users/eostrom/.rvm/gems/ruby-1.9.2-p290@iowl/gems/railties-3.2.6/lib/rails/commands/generate.rb:12:in `<top (required)>'
    from /Users/eostrom/.rvm/gems/ruby-1.9.2-p290@iowl/gems/activesupport-3.2.6/lib/active_support/dependencies.rb:251:in `require'
    from /Users/eostrom/.rvm/gems/ruby-1.9.2-p290@iowl/gems/activesupport-3.2.6/lib/active_support/dependencies.rb:251:in `block in require'
    from /Users/eostrom/.rvm/gems/ruby-1.9.2-p290@iowl/gems/activesupport-3.2.6/lib/active_support/dependencies.rb:236:in `load_dependency'
    from /Users/eostrom/.rvm/gems/ruby-1.9.2-p290@iowl/gems/activesupport-3.2.6/lib/active_support/dependencies.rb:251:in `require'
    from /Users/eostrom/.rvm/gems/ruby-1.9.2-p290@iowl/gems/railties-3.2.6/lib/rails/commands.rb:29:in `<top (required)>'
    from script/rails:6:in `require'
    from script/rails:6:in `<main>'
```

The line in question is:

``` ruby
      if user.try(:forem_needs_moderation?)
```

If I try this in the console, it works fine:

``` ruby
1.9.2p290 :003 > Refinery::User.first.try(:forem_needs_moderation?)
  Refinery::User Load (0.2ms)  SELECT "refinery_users".* FROM "refinery_users" LIMIT 1
 => false 
```

... so I'm guessing the problem is that `lib/forem/user_class_extensions.rb` hasn't been loaded in the generator.

**Comment by eostrom** [comment]
Thinking further on this: It seems like the installer does a bunch of stuff that needs to be done by a single developer (creating the initializer, adding migrations, all of which will be added to git and checked out by others) and a couple of things that need to be done on each dev/test/production database (actually running the migrations) and that you might not even want on all of them (creating default topics and categories).

Maybe it would be better to keep the latter out of the generator, and instead provide a rake task that can be run to add seed data to each database that wants it?

**Comment by javiercr** [comment]
This same error happens when installing forem with Spree (using the Spree::User class). Any workaround?

**Comment by javiercr** [comment]
The wiki page for "Integration with Refinery::CMS" gives a workaround:

> If you get an error under Creating default forum and topic, it means #325 hasn't been fixed yet. You'll need to manually add this to config/routes.rb, before Refinery::Core::Engine:
> mount Forem::Engine, :at => "/forums"

**Comment by cwise** [comment]
That page in the wiki is blank.

**Comment by parndt** [comment]
The relevant section was placed inside the issue comment, are you having this issue @cwise ?

**Comment by cwise** [comment]
I found the solution just now and am past it. Thanks though! Really looking forward to having them live in harmony.

**Comment by radar** [comment]
@eostrom The point of the installer is to set up Forem for your application. It is not designed to be run more than once over the course of the entire application's lifestyle.

If anyone is still seeing this issue with the most recent versions of Forem, can you please show me a `Gemfile` which reproduces this problem?

Thanks!

**Comment by eostrom** [comment]
Right, but creating seed data _is_ something you want to do more than once (e.g., on multiple developer databases). I think that's why I suggested adding a rake task to do that outside of the generator context.

Anyway, it's not really relevant to the PR, just a thought I had.

**Comment by radar** [comment]
@eostrom Yes, seed data can be run once on every developer's database. I am not sure quite what you're suggesting other than moving the seed data out of `rails g forem:install`? Maybe that's all you're suggesting. To move it out of that and make it runnable with `rake db:seed`.

**Comment by eostrom** [comment]
Yeah, me either! That was a while ago! But moving the seed data out of
`rails g forem:install` sounds about right.

**Comment by radar** [comment]
Closing as "won't fix"
