### ISSUE TITLE
Can't install Forem with RefineryCMS

### ISSUE THREAD

**Issue by sfcgeorge** [rubysherpas/forem#335]
Hi,

I followed the instructions for installing Forem with Refinery, but when I run `rails g forem:install` I get some nasty errors:

```
/Users/Simon/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/bundler/gems/forem-616ca2dfd762/lib/forem.rb:34:in `const_get': wrong constant name Refinery::User (NameError)
        from /Users/Simon/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/bundler/gems/forem-616ca2dfd762/lib/forem.rb:34:in `user_class'
        from /Users/Simon/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/bundler/gems/forem-616ca2dfd762/lib/forem/user_class_extensions.rb:2:in `<top (required)>'
        from /Users/Simon/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/activesupport-3.2.9/lib/active_support/dependencies.rb:469:in `load'
        from /Users/Simon/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/activesupport-3.2.9/lib/active_support/dependencies.rb:469:in `block in load_file'
        from /Users/Simon/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/activesupport-3.2.9/lib/active_support/dependencies.rb:639:in `new_constants_in'
        from /Users/Simon/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/activesupport-3.2.9/lib/active_support/dependencies.rb:468:in `load_file'
        from /Users/Simon/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/activesupport-3.2.9/lib/active_support/dependencies.rb:353:in `require_or_load'
        from /Users/Simon/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/activesupport-3.2.9/lib/active_support/dependencies.rb:313:in `depend_on'
        from /Users/Simon/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/activesupport-3.2.9/lib/active_support/dependencies.rb:225:in `require_dependency'
        from /Users/Simon/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/bundler/gems/forem-616ca2dfd762/lib/forem/engine.rb:17:in `block in <class:Engine>'
        from /Users/Simon/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/activesupport-3.2.9/lib/active_support/callbacks.rb:451:in `_run__4409649257750761083__prepare__1924713200512487128__callbacks'
        from /Users/Simon/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/activesupport-3.2.9/lib/active_support/callbacks.rb:405:in `__run_callback'
        from /Users/Simon/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/activesupport-3.2.9/lib/active_support/callbacks.rb:385:in `_run_prepare_callbacks'
        from /Users/Simon/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/activesupport-3.2.9/lib/active_support/callbacks.rb:81:in `run_callbacks'
        from /Users/Simon/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/actionpack-3.2.9/lib/action_dispatch/middleware/reloader.rb:74:in `prepare!'
        from /Users/Simon/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/actionpack-3.2.9/lib/action_dispatch/middleware/reloader.rb:48:in `prepare!'
        from /Users/Simon/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/railties-3.2.9/lib/rails/application/finisher.rb:47:in `block in <module:Finisher>'
        from /Users/Simon/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/railties-3.2.9/lib/rails/initializable.rb:30:in `instance_exec'
        from /Users/Simon/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/railties-3.2.9/lib/rails/initializable.rb:30:in `run'
        from /Users/Simon/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/railties-3.2.9/lib/rails/initializable.rb:55:in `block in run_initializers'
        from /Users/Simon/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/railties-3.2.9/lib/rails/initializable.rb:54:in `each'
        from /Users/Simon/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/railties-3.2.9/lib/rails/initializable.rb:54:in `run_initializers'
        from /Users/Simon/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/railties-3.2.9/lib/rails/application.rb:136:in `initialize!'
        from /Users/Simon/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/railties-3.2.9/lib/rails/railtie/configurable.rb:30:in `method_missing'
        from /Users/Simon/Documents/Website/QLAQ/QLAQ/config/environment.rb:5:in `<top (required)>'
        from /Users/Simon/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/activesupport-3.2.9/lib/active_support/dependencies.rb:251:in `require'
        from /Users/Simon/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/activesupport-3.2.9/lib/active_support/dependencies.rb:251:in `block in require'
        from /Users/Simon/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/activesupport-3.2.9/lib/active_support/dependencies.rb:236:in `load_dependency'
        from /Users/Simon/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/activesupport-3.2.9/lib/active_support/dependencies.rb:251:in `require'
        from /Users/Simon/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/railties-3.2.9/lib/rails/application.rb:103:in `require_environment!'
        from /Users/Simon/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/railties-3.2.9/lib/rails/commands.rb:25:in `<top (required)>'
        from script/rails:6:in `require'
        from script/rails:6:in `<main>'
```

I think I have the user class set correctly:

```
Forem.user_class = "Refinery::User"
```

Here's the result of running `rake db:migrate` directly:

```
rake db:migrate
rake aborted!
wrong constant name Refinery::User
/Users/Simon/Documents/Website/QLAQ/QLAQ/config/environment.rb:5:in `<top (required)>'
```

It looks like issue #88 might be related, but I'm really not sure what to do from here. Any thoughts and help would be greatly appreciated. Let me know if you need any extra information.

Thanks

**Comment by Kardans** [comment]
Same here!

**Comment by parndt** [comment]
What happens if you place Refinery _after_ Forem in the Gemfile and what happens if it's _before_?

**Comment by sfcgeorge** [comment]
Sadly exactly the same error either way. I created the Refinery app fresh rather than adding to an existing Rails app if that helps. I also tried deleting the app and starting fresh but no change. Using the latest versions of every gem, tried refinery 2.0.8 and 2.0.9 with the same results. I've also tried "User", "::User", "::Refinery::User" with varying errors. Also tried with and without the line added to the gemfile with no change.

**Comment by sfcgeorge** [comment]
If it helps your debugging I've also pushed the app to Github:  https://github.com/sfcgeorge/QLAQ
Any help welcome

**Comment by sfcgeorge** [comment]
Thank you very much, everything working as expected now. Perfect :smile:

**Comment by Kardans** [comment]
So what should I put instead of "Refinery::User" now?

**Comment by sfcgeorge** [comment]
Do a `bundle update` then it should work fine. It is still `"Refinery::User"` for class and `current_refinery_user` for current_user method.
