### ISSUE TITLE
migrate error when user exist in table

### ISSUE THREAD

**Issue by nordbit** [rubysherpas/forem#343]
gems/activemodel-3.2.9/lib/active_model/attribute_methods.rb:407:in `method_missing': undefined method`forem_needs_moderation?' for #User:0x000000045a4890 (NoMethodError)

**Comment by radar** [comment]
This issue does not provide enough information in order to accurately reproduce it. Please provide steps to reproduce this issue.

**Comment by giedriusr** [comment]
Hi @radar,

I just got the same error. Will try to be more descriptive.

Environment
Rails: 3.2.9
Ruby: 1.9.3-p194

I already have User model (using Devise). Just ran the command:
rails g forem:install

I am using PostgreSQL for DB. If you need extra information, please let me know. I'd like to help solve this issue. Maybe I am the only one experiencing this.

``` bash
$ rails g forem:install
Copying over Forem migrations...
What is your user class called? [User] 
What is the current_user helper called in your app? [current_user] 
Defining forem_user method inside ApplicationController...
      insert  app/controllers/application_controller.rb
Adding forem initializer (config/initializers/forem.rb)...
      create  config/initializers/forem.rb
Running rake db:migrate
NOTICE:  CREATE TABLE will create implicit sequence "forem_forums_id_seq" for serial column "forem_forums.id"
NOTICE:  CREATE TABLE / PRIMARY KEY will create implicit index "forem_forums_pkey" for table "forem_forums"
NOTICE:  CREATE TABLE will create implicit sequence "forem_topics_id_seq" for serial column "forem_topics.id"
NOTICE:  CREATE TABLE / PRIMARY KEY will create implicit index "forem_topics_pkey" for table "forem_topics"
NOTICE:  CREATE TABLE will create implicit sequence "forem_posts_id_seq" for serial column "forem_posts.id"
NOTICE:  CREATE TABLE / PRIMARY KEY will create implicit index "forem_posts_pkey" for table "forem_posts"
NOTICE:  CREATE TABLE will create implicit sequence "forem_views_id_seq" for serial column "forem_views.id"
NOTICE:  CREATE TABLE / PRIMARY KEY will create implicit index "forem_views_pkey" for table "forem_views"
NOTICE:  CREATE TABLE will create implicit sequence "forem_categories_id_seq" for serial column "forem_categories.id"
NOTICE:  CREATE TABLE / PRIMARY KEY will create implicit index "forem_categories_pkey" for table "forem_categories"
NOTICE:  CREATE TABLE will create implicit sequence "forem_subscriptions_id_seq" for serial column "forem_subscriptions.id"
NOTICE:  CREATE TABLE / PRIMARY KEY will create implicit index "forem_subscriptions_pkey" for table "forem_subscriptions"
NOTICE:  CREATE TABLE will create implicit sequence "forem_groups_id_seq" for serial column "forem_groups.id"
NOTICE:  CREATE TABLE / PRIMARY KEY will create implicit index "forem_groups_pkey" for table "forem_groups"
NOTICE:  CREATE TABLE will create implicit sequence "forem_memberships_id_seq" for serial column "forem_memberships.id"
NOTICE:  CREATE TABLE / PRIMARY KEY will create implicit index "forem_memberships_pkey" for table "forem_memberships"
NOTICE:  CREATE TABLE will create implicit sequence "forem_moderator_groups_id_seq" for serial column "forem_moderator_groups.id"
NOTICE:  CREATE TABLE / PRIMARY KEY will create implicit index "forem_moderator_groups_pkey" for table "forem_moderator_groups"
Creating default forum and topic
/Users/giedrius/.rvm/gems/ruby-1.9.3-p194/gems/activemodel-3.2.9/lib/active_model/attribute_methods.rb:407:in `method_missing': undefined method `forem_needs_moderation?' for #<User:0x007fcc5b600fc0> (NoMethodError)
```

**Comment by radar** [comment]
@giedriusr: Thank you. I will take a look at this issue when I have time later.

**Comment by giedriusr** [comment]
Ok, thank you very much! :)

**Comment by willcosgrove** [comment]
I'm in the same boat, having the same problem.  User model with Devise, running on Postgres.  Exact same error.

**Comment by radar** [comment]
Hi will,

Could you please look into this issue for us? I am sure it's something simple that we've messed up. Shouldn't take up too much of your time.

Thanks!

**Comment by willcosgrove** [comment]
It looks like it's happening in the `Forem::Engine.load_seed` call.  Nothing is sticking out to me as blatantly wrong in the `seeds.rb` file.  After I got this error, I was able to just fire up a rails console and run `Forem::Engine.load_seed` just fine.  So my naive guess would be to say that maybe something wasn't completely loaded, like maybe from the forem initializer.  But I may be way off.

I'll try taking another look tomorrow when I'm less tired.

**Comment by parndt** [comment]
Maybe some caching is killing things?

**Comment by JasonTolliver** [comment]
I had this same issue.  I wasn't able, like @willcosgrove, to simply call Forem::Engine.load_seed from the console. After a bit of investigation, I realized that [gem-location]/lib/forem/user_class_extensions.rb hadn't been properly loaded.  Once I loaded that path, user.forem_needs_moderation? ran just fine.

In any case, not sure if this is the fix for the gem itself, but I hope it'll point you in the right direction.  I'm just going to manually run the install generator code piece by piece from here.

**Comment by jayshepherd** [comment]
Just ran into this myself, running twice as per #360 also worked for me.
