### ISSUE TITLE
superclass mismatch for class MembersController

### ISSUE THREAD

**Issue by ricardohsd** [rubysherpas/forem#356]
Hi guys,

I have a project using rails 3.2.6 and only in production I get the following error:

```
E, [2012-12-22T12:36:21.454508 #2897] ERROR -- : superclass mismatch for class MembersController (TypeError)
/Users/ricardohsd/.rvm/gems/ruby-1.9.3-head/bundler/gems/forem-76c49b2ec89a/app/controllers/forem/admin/members_controller.rb:2:in `<module:Forem>'
/Users/ricardohsd/.rvm/gems/ruby-1.9.3-head/bundler/gems/forem-76c49b2ec89a/app/controllers/forem/admin/members_controller.rb:1:in `<top (required)>'
```

I tried to fix without success.

**Comment by radar** [comment]
I think I've fixed this up with 03725d78827c235574b0186350316821c880a7e9 now. Could you please run `bundle update forem` and try again?
