### ISSUE TITLE
Migration fails with "can't convert string into integer"

### ISSUE THREAD

**Issue by masterweily** [rubysherpas/forem#384]
hi, 
just trying to install forem in a simple application, but the migration fails

```
$ rails g forem:install
What is your user class called? [User] 
What is the current_user helper called in your app? [current_user] 
Defining forem_user method inside ApplicationController...
      insert  app/controllers/application_controller.rb
Adding forem initializer (config/initializers/forem.rb)...
      create  config/initializers/forem.rb
Running rake db:migrate
rake aborted!
can't convert String into Integer
/home/yaron/.rvm/gems/ruby-1.9.3-p385/gems/activesupport-3.2.11/lib/active_support/descendants_tracker.rb:12:in `descendants'
/home/yaron/.rvm/gems/ruby-1.9.3-p385/gems/activesupport-3.2.11/lib/active_support/callbacks.rb:425:in `__update_callbacks'
/home/yaron/.rvm/gems/ruby-1.9.3-p385/gems/activesupport-3.2.11/lib/active_support/callbacks.rb:494:in `set_callback'
/home/yaron/.rvm/gems/ruby-1.9.3-p385/gems/activemodel-3.2.11/lib/active_model/callbacks.rb:110:in `before_save'
/home/yaron/.rvm/gems/ruby-1.9.3-p385/gems/activerecord-3.2.11/lib/active_record/autosave_association.rb:189:in `add_autosave_association_callbacks'
/home/yaron/.rvm/gems/ruby-1.9.3-p385/gems/activerecord-3.2.11/lib/active_record/autosave_association.rb:140:in `build'
/home/yaron/.rvm/gems/ruby-1.9.3-p385/gems/activerecord-3.2.11/lib/active_record/associations/builder/has_many.rb:10:in `build'
/home/yaron/.rvm/gems/ruby-1.9.3-p385/gems/activerecord-3.2.11/lib/active_record/associations/builder/collection_association.rb:13:in `build'
/home/yaron/.rvm/gems/ruby-1.9.3-p385/gems/activerecord-3.2.11/lib/active_record/associations.rb:1198:in `has_many'
/home/yaron/.rvm/gems/ruby-1.9.3-p385/bundler/gems/forem-b46cad2eb975/app/decorators/lib/forem/user_class_decorator.rb:7:in `block in <top (required)>'
/home/yaron/.rvm/gems/ruby-1.9.3-p385/bundler/gems/forem-b46cad2eb975/app/decorators/lib/forem/user_class_decorator.rb:3:in `class_eval'
/home/yaron/.rvm/gems/ruby-1.9.3-p385/bundler/gems/forem-b46cad2eb975/app/decorators/lib/forem/user_class_decorator.rb:3:in `<top (required)>'
/home/yaron/.rvm/gems/ruby-1.9.3-p385/gems/activesupport-3.2.11/lib/active_support/dependencies.rb:245:in `load'
/home/yaron/.rvm/gems/ruby-1.9.3-p385/gems/activesupport-3.2.11/lib/active_support/dependencies.rb:245:in `block in load'
/home/yaron/.rvm/gems/ruby-1.9.3-p385/gems/activesupport-3.2.11/lib/active_support/dependencies.rb:236:in `load_dependency'
/home/yaron/.rvm/gems/ruby-1.9.3-p385/gems/activesupport-3.2.11/lib/active_support/dependencies.rb:245:in `load'
/home/yaron/.rvm/gems/ruby-1.9.3-p385/gems/decorators-1.0.3/lib/decorators.rb:11:in `block in load!'
/home/yaron/.rvm/gems/ruby-1.9.3-p385/gems/decorators-1.0.3/lib/decorators.rb:7:in `each'
/home/yaron/.rvm/gems/ruby-1.9.3-p385/gems/decorators-1.0.3/lib/decorators.rb:7:in `load!'
/home/yaron/.rvm/gems/ruby-1.9.3-p385/gems/decorators-1.0.3/lib/decorators/railtie.rb:7:in `block in <class:Railtie>'
/home/yaron/.rvm/gems/ruby-1.9.3-p385/gems/activesupport-3.2.11/lib/active_support/callbacks.rb:440:in `_run__760868406__prepare__881577636__callbacks'
/home/yaron/.rvm/gems/ruby-1.9.3-p385/gems/activesupport-3.2.11/lib/active_support/callbacks.rb:405:in `__run_callback'
/home/yaron/.rvm/gems/ruby-1.9.3-p385/gems/activesupport-3.2.11/lib/active_support/callbacks.rb:385:in `_run_prepare_callbacks'
/home/yaron/.rvm/gems/ruby-1.9.3-p385/gems/activesupport-3.2.11/lib/active_support/callbacks.rb:81:in `run_callbacks'
/home/yaron/.rvm/gems/ruby-1.9.3-p385/gems/actionpack-3.2.11/lib/action_dispatch/middleware/reloader.rb:74:in `prepare!'
/home/yaron/.rvm/gems/ruby-1.9.3-p385/gems/actionpack-3.2.11/lib/action_dispatch/middleware/reloader.rb:48:in `prepare!'
/home/yaron/.rvm/gems/ruby-1.9.3-p385/gems/railties-3.2.11/lib/rails/application/finisher.rb:47:in `block in <module:Finisher>'
/home/yaron/.rvm/gems/ruby-1.9.3-p385/gems/railties-3.2.11/lib/rails/initializable.rb:30:in `instance_exec'
/home/yaron/.rvm/gems/ruby-1.9.3-p385/gems/railties-3.2.11/lib/rails/initializable.rb:30:in `run'
/home/yaron/.rvm/gems/ruby-1.9.3-p385/gems/railties-3.2.11/lib/rails/initializable.rb:55:in `block in run_initializers'
/home/yaron/.rvm/gems/ruby-1.9.3-p385/gems/railties-3.2.11/lib/rails/initializable.rb:54:in `each'
/home/yaron/.rvm/gems/ruby-1.9.3-p385/gems/railties-3.2.11/lib/rails/initializable.rb:54:in `run_initializers'
/home/yaron/.rvm/gems/ruby-1.9.3-p385/gems/railties-3.2.11/lib/rails/application.rb:136:in `initialize!'
/home/yaron/.rvm/gems/ruby-1.9.3-p385/gems/railties-3.2.11/lib/rails/railtie/configurable.rb:30:in `method_missing'
/var/www/sites-on-rails/GoLawyer.co.il.2/config/environment.rb:5:in `<top (required)>'
/home/yaron/.rvm/gems/ruby-1.9.3-p385/gems/activesupport-3.2.11/lib/active_support/dependencies.rb:251:in `require'
/home/yaron/.rvm/gems/ruby-1.9.3-p385/gems/activesupport-3.2.11/lib/active_support/dependencies.rb:251:in `block in require'
/home/yaron/.rvm/gems/ruby-1.9.3-p385/gems/activesupport-3.2.11/lib/active_support/dependencies.rb:236:in `load_dependency'
/home/yaron/.rvm/gems/ruby-1.9.3-p385/gems/activesupport-3.2.11/lib/active_support/dependencies.rb:251:in `require'
/home/yaron/.rvm/gems/ruby-1.9.3-p385/gems/railties-3.2.11/lib/rails/application.rb:103:in `require_environment!'
/home/yaron/.rvm/gems/ruby-1.9.3-p385/gems/railties-3.2.11/lib/rails/application.rb:297:in `block (2 levels) in initialize_tasks'
/home/yaron/.rvm/gems/ruby-1.9.3-p385/bin/ruby_noexec_wrapper:14:in `eval'
/home/yaron/.rvm/gems/ruby-1.9.3-p385/bin/ruby_noexec_wrapper:14:in `<main>'
Tasks: TOP => db:migrate => environment
(See full trace by running task with --trace)
Creating default forum and topic
/home/yaron/.rvm/gems/ruby-1.9.3-p385/gems/activerecord-3.2.11/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:245:in `query': Mysql2::Error: Table 'go_lawyer_co_il_2_development.forem_categories' doesn't exist: SHOW FULL FIELDS FROM `forem_categories` (ActiveRecord::StatementInvalid)
    from /home/yaron/.rvm/gems/ruby-1.9.3-p385/gems/activerecord-3.2.11/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:245:in `block in execute'
    from /home/yaron/.rvm/gems/ruby-1.9.3-p385/gems/activerecord-3.2.11/lib/active_record/connection_adapters/abstract_adapter.rb:280:in `block in log'
    from /home/yaron/.rvm/gems/ruby-1.9.3-p385/gems/activesupport-3.2.11/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
    from /home/yaron/.rvm/gems/ruby-1.9.3-p385/gems/activerecord-3.2.11/lib/active_record/connection_adapters/abstract_adapter.rb:275:in `log'
    from /home/yaron/.rvm/gems/ruby-1.9.3-p385/gems/activerecord-3.2.11/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:245:in `execute'
    from /home/yaron/.rvm/gems/ruby-1.9.3-p385/gems/activerecord-3.2.11/lib/active_record/connection_adapters/mysql2_adapter.rb:211:in `execute'
    from /home/yaron/.rvm/gems/ruby-1.9.3-p385/gems/activerecord-3.2.11/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:259:in `execute_and_free'
    from /home/yaron/.rvm/gems/ruby-1.9.3-p385/gems/activerecord-3.2.11/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:426:in `columns'
    from /home/yaron/.rvm/gems/ruby-1.9.3-p385/gems/activerecord-3.2.11/lib/active_record/connection_adapters/schema_cache.rb:12:in `block in initialize'
    from /home/yaron/.rvm/gems/ruby-1.9.3-p385/gems/activerecord-3.2.11/lib/active_record/model_schema.rb:228:in `yield'
    from /home/yaron/.rvm/gems/ruby-1.9.3-p385/gems/activerecord-3.2.11/lib/active_record/model_schema.rb:228:in `default'
    from /home/yaron/.rvm/gems/ruby-1.9.3-p385/gems/activerecord-3.2.11/lib/active_record/model_schema.rb:228:in `columns'
    from /home/yaron/.rvm/gems/ruby-1.9.3-p385/gems/activerecord-3.2.11/lib/active_record/model_schema.rb:243:in `column_defaults'
    from /home/yaron/.rvm/gems/ruby-1.9.3-p385/gems/activerecord-3.2.11/lib/active_record/base.rb:482:in `initialize'
    from /home/yaron/.rvm/gems/ruby-1.9.3-p385/gems/activerecord-3.2.11/lib/active_record/persistence.rb:44:in `new'
    from /home/yaron/.rvm/gems/ruby-1.9.3-p385/gems/activerecord-3.2.11/lib/active_record/persistence.rb:44:in `create'
    from /home/yaron/.rvm/gems/ruby-1.9.3-p385/bundler/gems/forem-b46cad2eb975/db/seeds.rb:1:in `<top (required)>'
    from /home/yaron/.rvm/gems/ruby-1.9.3-p385/gems/activesupport-3.2.11/lib/active_support/dependencies.rb:245:in `load'
    from /home/yaron/.rvm/gems/ruby-1.9.3-p385/gems/activesupport-3.2.11/lib/active_support/dependencies.rb:245:in `block in load'
    from /home/yaron/.rvm/gems/ruby-1.9.3-p385/gems/activesupport-3.2.11/lib/active_support/dependencies.rb:236:in `load_dependency'
    from /home/yaron/.rvm/gems/ruby-1.9.3-p385/gems/activesupport-3.2.11/lib/active_support/dependencies.rb:245:in `load'
    from /home/yaron/.rvm/gems/ruby-1.9.3-p385/gems/railties-3.2.11/lib/rails/engine.rb:520:in `load_seed'
    from /home/yaron/.rvm/gems/ruby-1.9.3-p385/gems/railties-3.2.11/lib/rails/railtie/configurable.rb:30:in `method_missing'
    from /home/yaron/.rvm/gems/ruby-1.9.3-p385/bundler/gems/forem-b46cad2eb975/lib/generators/forem/install_generator.rb:67:in `seed_database'
    from /home/yaron/.rvm/gems/ruby-1.9.3-p385/gems/thor-0.17.0/lib/thor/task.rb:27:in `run'
    from /home/yaron/.rvm/gems/ruby-1.9.3-p385/gems/thor-0.17.0/lib/thor/invocation.rb:120:in `invoke_task'
    from /home/yaron/.rvm/gems/ruby-1.9.3-p385/gems/thor-0.17.0/lib/thor/invocation.rb:126:in `block in invoke_all'
    from /home/yaron/.rvm/gems/ruby-1.9.3-p385/gems/thor-0.17.0/lib/thor/invocation.rb:126:in `each'
    from /home/yaron/.rvm/gems/ruby-1.9.3-p385/gems/thor-0.17.0/lib/thor/invocation.rb:126:in `map'
    from /home/yaron/.rvm/gems/ruby-1.9.3-p385/gems/thor-0.17.0/lib/thor/invocation.rb:126:in `invoke_all'
    from /home/yaron/.rvm/gems/ruby-1.9.3-p385/gems/thor-0.17.0/lib/thor/group.rb:238:in `dispatch'
    from /home/yaron/.rvm/gems/ruby-1.9.3-p385/gems/thor-0.17.0/lib/thor/base.rb:434:in `start'
    from /home/yaron/.rvm/gems/ruby-1.9.3-p385/gems/railties-3.2.11/lib/rails/generators.rb:171:in `invoke'
    from /home/yaron/.rvm/gems/ruby-1.9.3-p385/gems/railties-3.2.11/lib/rails/commands/generate.rb:12:in `<top (required)>'
    from /home/yaron/.rvm/gems/ruby-1.9.3-p385/gems/activesupport-3.2.11/lib/active_support/dependencies.rb:251:in `require'
    from /home/yaron/.rvm/gems/ruby-1.9.3-p385/gems/activesupport-3.2.11/lib/active_support/dependencies.rb:251:in `block in require'
    from /home/yaron/.rvm/gems/ruby-1.9.3-p385/gems/activesupport-3.2.11/lib/active_support/dependencies.rb:236:in `load_dependency'
    from /home/yaron/.rvm/gems/ruby-1.9.3-p385/gems/activesupport-3.2.11/lib/active_support/dependencies.rb:251:in `require'
    from /home/yaron/.rvm/gems/ruby-1.9.3-p385/gems/railties-3.2.11/lib/rails/commands.rb:29:in `<top (required)>'
    from script/rails:6:in `require'
    from script/rails:6:in `<main>'
```

**Comment by parndt** [comment]
Notes: Seems like a problem with a decorator at first glance

**Comment by parndt** [comment]
Something here
https://github.com/radar/forem/blob/master/app/decorators/lib/forem/user_class_decorator.rb#L7

**Comment by masterweily** [comment]
tnx, any idea what can i do about it?

**Comment by parndt** [comment]
Not currently but I can try to reproduce tomorrow or the next day. I
don't have a computer at the moment :)

**Comment by ghost** [comment]
(aka: masterweily ;)

hi,
thanks for all the help so far, but after struggling with it for a while i still facing the same problem, and i really don't know what is so special about my configurations that it seems to happen only to me (did not dig much into the code of the gem itself).

if anyone can reproduce it or give me any hint about what is going on here i will be grateful

``` bash
$ ruby -v 
ruby 1.9.3p362 (2012-12-25 revision 38607) [x86_64-linux]
```

<b>Gemfile</b>

``` ruby
source 'https://rubygems.org'

gem 'rails', '3.2.11'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem 'mysql2'


gem 'rmagick'                                       # image manipulations, (self || minimagic) required by 'carrierwave' gem
gem 'carrierwave'                               # image atachment to models
gem 'easy_roles'                            # users roles
gem 'forem', :git => "git://github.com/radar/forem.git"  # forum plugin
gem 'kaminari'                  # support pagination ( self || will_paginate ) required by forem


# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'

  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  gem 'therubyracer', :platforms => :ruby

  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails'

group :development do
  gem 'faker'             #  fake some data, good for stubs, testing, and prototyping
  gem 'binding_of_caller' #  NOT IN PRODUCTION !!!
  gem 'better_errors'     #  NOT IN PRODUCTION !!!
  gem 'sextant'           #  NOT IN PRODUCTION !!! show routes in localhost:3000/rails/routes
end
```

p.s 
tried that in two different machines, both running linux

**Comment by radar** [comment]
Could you please show the error that you're seeing?

**Comment by parndt** [comment]
@widexposure please update your ruby to the latest patch level. I seem to remember lots of segfaults with p362

**Comment by ghost** [comment]
thanks, 
i will try with latest ruby, so far i tried with p362 and p385 (in two different machines) and both gave me the same error.
@radar the error is as shown in the original post by masterweily, sorry about the confusion, i use both usernames

**Comment by radar** [comment]
I wasn't able to reproduce this issue on my machine tonight. Sorry! Here's what I tried:

1) Generated a new Rails app
2) Added latest Devise and Kaminari to Gemfile
3) Ran `rails g devise:install`, `rails g devise user` to set up a User model
4) Added Forem to gemfile
5) Ran `rails g forem:install`. Everything went to plan.

Are you still able to do it with the latest Forem @widexposure?

**Comment by ghost** [comment]
Ok, followed @radar steps and it worked well for a new application.  must say it is pretty awesome staff.

my goal now is to include forem into an existing project without devise.  I guess something is wrong with my User model.  As much as i understood forem doesn't care about my auth method, as long there are User model and current_user helper, both implemented in the project.  is there anything else that i'm missing?

thanks for the help so far

**Comment by ghost** [comment]
solved!

something was really wrong with my User model, and it had nothing to do with forem.

i have defined method User.hash, that overridden Object.hash, and caused User.has_many to fail.

should have seen it right from the start, thanks a lot :-)

**Comment by radar** [comment]
I don't understand why you would override such a critical method to begin with. Seems like you really shot yourself in the foot on this one :\
