### ISSUE TITLE
cannot load such file -- localeapp/rails (LoadError)

### ISSUE THREAD

**Issue by nazrulcse** [rubysherpas/forem#414]
Hello
When i try to install forem "rails g forem:install" it shows me following error

```
C:/Ruby193/lib/ruby/gems/1.9.1/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:251:
in `require': cannot load such file -- localeapp/rails (LoadError)
```

anyone can you please help me.

Thank you

**Comment by parndt** [comment]
Has it ever worked before?

**Comment by nazrulcse** [comment]
yes

**Comment by parndt** [comment]
What changed? Can you please give a little more information to aid in debugging?

**Comment by parndt** [comment]
Okay, I can reproduce using my own means.

**Comment by nazrulcse** [comment]
I have a rails project on rails 3.0.9 and i try to add forem but i see that forem is depends on rails 3.1 or 3.2 so i have upgrade my project int rails 3.2.13 and try to add forem.

My Gemfile

``` ruby
gem 'mysql2'
gem 'mongo_mapper'
gem 'activerecord'
gem 'haml'
gem 'haml-rails'
gem 'kaminari', '0.13.0'
gem 'carrierwave'
gem 'mini_magick'
gem 'fog'
gem 'htmlentities'
gem "bson_ext"
gem "activeadmin"
gem 'forem', :github => 'https://github.com/radar/forem.git'
```

Error

``` shell
C:\Users\Nazrul\ugl>rails g forem:install
C:/Ruby193/lib/ruby/gems/1.9.1/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:251:in `require': cannot load such fil
e -- localeapp/rails (LoadError)
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:251:in `block in require'

        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:236:in `load_dependency'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:251:in `require'
        from C:/Ruby193/lib/ruby/gems/1.9.1/bundler/gems/forem-704f88ccbd7b/lib/forem/engine.rb:24:in `block in <class:Engine>'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/railties-3.2.13/lib/rails/initializable.rb:30:in `instance_exec'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/railties-3.2.13/lib/rails/initializable.rb:30:in `run'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/railties-3.2.13/lib/rails/initializable.rb:55:in `block in run_initializers'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/railties-3.2.13/lib/rails/initializable.rb:54:in `each'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/railties-3.2.13/lib/rails/initializable.rb:54:in `run_initializers'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/railties-3.2.13/lib/rails/application.rb:136:in `initialize!'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/railties-3.2.13/lib/rails/railtie/configurable.rb:30:in `method_missing'
        from C:/Users/Nazrul/ugl/config/environment.rb:5:in `<top (required)>'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:251:in `require'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:251:in `block in require'

        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:236:in `load_dependency'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:251:in `require'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/railties-3.2.13/lib/rails/application.rb:103:in `require_environment!'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/railties-3.2.13/lib/rails/commands.rb:25:in `<top (required)>'
        from script/rails:6:in `require'
        from script/rails:6:in `<main>'
```

**Comment by nazrulcse** [comment]
I don't understand can you please expand it to me.

**Comment by parndt** [comment]
I fixed the issue, please run `bundle update --source forem` and the problem should be gone.

**Comment by nazrulcse** [comment]
Thank you
This problem is solved.
