### ISSUE TITLE
RestClient::NotAcceptable (406 Not Acceptable):

### ISSUE THREAD

**Issue by nazrulcse** [rubysherpas/forem#416]
Forem install successfully but when i run the project it shows me following error:

```
Started GET "/forums" for 127.0.0.1 at 2013-04-30 21:57:31 -0600
Processing by Forem::ForumsController#index as HTML
** [Localeapp] 1367380652 - Handling translation updates
** [Localeapp] 1367380652 - polling
** [Localeapp] API CALL: get https://api.localeapp.com/v1/projects//translations.yml?updated_at=1367360407
** [Localeapp] ATTEMPT 1
Completed 500 Internal Server Error in 1720ms

RestClient::NotAcceptable (406 Not Acceptable):
```

can anyone please help me.

**Comment by boatmon0** [comment]
I have the same error, might have something to do with rails 3.2.13 and ruby 1.9.3p392.  

Trace:

```
rest-client (1.6.7) lib/restclient/abstract_response.rb:48:in `return!'
rest-client (1.6.7) lib/restclient/request.rb:230:in `process_result'
rest-client (1.6.7) lib/restclient/request.rb:178:in `block in transmit'
/home/eugene/.rvm/rubies/ruby-1.9.3-p392/lib/ruby/1.9.1/net/http.rb:745:in `start'
rest-client (1.6.7) lib/restclient/request.rb:172:in `transmit'
rest-client (1.6.7) lib/restclient/request.rb:64:in `execute'
rest-client (1.6.7) lib/restclient/request.rb:33:in `execute'
localeapp (0.6.9) lib/localeapp/api_caller.rb:67:in `make_call'
localeapp (0.6.9) lib/localeapp/api_caller.rb:28:in `call'
localeapp (0.6.9) lib/localeapp/api_call.rb:6:in `api_call'
localeapp (0.6.9) lib/localeapp/poller.rb:43:in `poll!'
localeapp (0.6.9) lib/localeapp/rails/controller.rb:14:in `handle_translation_updates'
activesupport (3.2.13) lib/active_support/callbacks.rb:418:in `_run__324363186__process_action__350408264__callbacks'
activesupport (3.2.13) lib/active_support/callbacks.rb:405:in `__run_callback'
activesupport (3.2.13) lib/active_support/callbacks.rb:385:in `_run_process_action_callbacks'
activesupport (3.2.13) lib/active_support/callbacks.rb:81:in `run_callbacks'
actionpack (3.2.13) lib/abstract_controller/callbacks.rb:17:in `process_action'
actionpack (3.2.13) lib/action_controller/metal/rescue.rb:29:in `process_action'
actionpack (3.2.13) lib/action_controller/metal/instrumentation.rb:30:in `block in process_action'
activesupport (3.2.13) lib/active_support/notifications.rb:123:in `block in instrument'
activesupport (3.2.13) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
activesupport (3.2.13) lib/active_support/notifications.rb:123:in `instrument'
actionpack (3.2.13) lib/action_controller/metal/instrumentation.rb:29:in `process_action'
actionpack (3.2.13) lib/action_controller/metal/params_wrapper.rb:207:in `process_action'
activerecord (3.2.13) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
actionpack (3.2.13) lib/abstract_controller/base.rb:121:in `process'
actionpack (3.2.13) lib/abstract_controller/rendering.rb:45:in `process'
actionpack (3.2.13) lib/action_controller/metal.rb:203:in `dispatch'
actionpack (3.2.13) lib/action_controller/metal/rack_delegation.rb:14:in `dispatch'
actionpack (3.2.13) lib/action_controller/metal.rb:246:in `block in action'
actionpack (3.2.13) lib/action_dispatch/routing/route_set.rb:73:in `call'
actionpack (3.2.13) lib/action_dispatch/routing/route_set.rb:73:in `dispatch'
actionpack (3.2.13) lib/action_dispatch/routing/route_set.rb:36:in `call'
journey (1.0.4) lib/journey/router.rb:68:in `block in call'
journey (1.0.4) lib/journey/router.rb:56:in `each'
journey (1.0.4) lib/journey/router.rb:56:in `call'
actionpack (3.2.13) lib/action_dispatch/routing/route_set.rb:612:in `call'
actionpack (3.2.13) lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
rack (1.4.5) lib/rack/etag.rb:23:in `call'
rack (1.4.5) lib/rack/conditionalget.rb:25:in `call'
actionpack (3.2.13) lib/action_dispatch/middleware/head.rb:14:in `call'
actionpack (3.2.13) lib/action_dispatch/middleware/params_parser.rb:21:in `call'
actionpack (3.2.13) lib/action_dispatch/middleware/flash.rb:242:in `call'
rack (1.4.5) lib/rack/session/abstract/id.rb:210:in `context'
rack (1.4.5) lib/rack/session/abstract/id.rb:205:in `call'
actionpack (3.2.13) lib/action_dispatch/middleware/cookies.rb:341:in `call'
activerecord (3.2.13) lib/active_record/query_cache.rb:64:in `call'
activerecord (3.2.13) lib/active_record/connection_adapters/abstract/connection_pool.rb:479:in `call'
actionpack (3.2.13) lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
activesupport (3.2.13) lib/active_support/callbacks.rb:405:in `_run__332767350__call__828226316__callbacks'
activesupport (3.2.13) lib/active_support/callbacks.rb:405:in `__run_callback'
activesupport (3.2.13) lib/active_support/callbacks.rb:385:in `_run_call_callbacks'
activesupport (3.2.13) lib/active_support/callbacks.rb:81:in `run_callbacks'
actionpack (3.2.13) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
actionpack (3.2.13) lib/action_dispatch/middleware/reloader.rb:65:in `call'
actionpack (3.2.13) lib/action_dispatch/middleware/remote_ip.rb:31:in `call'
actionpack (3.2.13) lib/action_dispatch/middleware/debug_exceptions.rb:16:in `call'
actionpack (3.2.13) lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
railties (3.2.13) lib/rails/rack/logger.rb:32:in `call_app'
railties (3.2.13) lib/rails/rack/logger.rb:16:in `block in call'
activesupport (3.2.13) lib/active_support/tagged_logging.rb:22:in `tagged'
railties (3.2.13) lib/rails/rack/logger.rb:16:in `call'
actionpack (3.2.13) lib/action_dispatch/middleware/request_id.rb:22:in `call'
rack (1.4.5) lib/rack/methodoverride.rb:21:in `call'
rack (1.4.5) lib/rack/runtime.rb:17:in `call'
activesupport (3.2.13) lib/active_support/cache/strategy/local_cache.rb:72:in `call'
rack (1.4.5) lib/rack/lock.rb:15:in `call'
actionpack (3.2.13) lib/action_dispatch/middleware/static.rb:63:in `call'
railties (3.2.13) lib/rails/engine.rb:479:in `call'
railties (3.2.13) lib/rails/application.rb:223:in `call'
rack (1.4.5) lib/rack/content_length.rb:14:in `call'
railties (3.2.13) lib/rails/rack/log_tailer.rb:17:in `call'
rack (1.4.5) lib/rack/handler/webrick.rb:59:in `service'
/home/eugene/.rvm/rubies/ruby-1.9.3-p392/lib/ruby/1.9.1/webrick/httpserver.rb:138:in `service'
/home/eugene/.rvm/rubies/ruby-1.9.3-p392/lib/ruby/1.9.1/webrick/httpserver.rb:94:in `run'
/home/eugene/.rvm/rubies/ruby-1.9.3-p392/lib/ruby/1.9.1/webrick/server.rb:191:in `block in start_thread'
```

**Comment by parndt** [comment]
Seems related to localeapp integration to me

**Comment by parndt** [comment]
Note the double / in the following API call. This looks like the project id is not included in the URL properly:

```
** [Localeapp] API CALL: get https://api.localeapp.com/v1/projects//translations.yml?updated_at=1367360407
```

**Comment by boatmon0** [comment]
Thanks parndt, not ever used localeapp myself, got any suggestions?

**Comment by parndt** [comment]
No, it should just work from your perspective. I'm just providing debug information :)

**Comment by nazrulcse** [comment]
Hello parndt

 Can you please suggest me about localeapp and why our project it is not integrate it's request url, forem gem/engine depends on localeapp but in our project we are not using it. can you please help?

thanks

**Comment by parndt** [comment]
Forem is depending on localeapp, so in your project you are using it. If I could help immediately then I would have. :)

**Comment by nazrulcse** [comment]
can you please help how can i skip/disabled this pulling request for localeapp?

**Comment by parndt** [comment]
@nazrulcse the nature of an issue means that if people can help to provide workarounds they will help.. you don't need to request it. We're not ignoring you, we just don't yet know the answer.

**Comment by radar** [comment]
@nazrulcse Please provide your Gemfile so that we can attempt to reproduce this problem locally.

**Comment by boatmon0** [comment]
Here is my Gemfile, perhaps it will help.

``` ruby
source 'https://rubygems.org'

gem 'rails', '3.2.13'

gem 'mysql2'

gem 'cocaine'
gem 'spreadsheet'
gem 'paperclip'
gem 'mail'
gem "acts_as_list"
gem 'recaptcha', :require => 'recaptcha/rails'
gem "googlecharts", "~> 1.6.8"
#  gem 'sass-rails', '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'compass-rails'
  gem 'jquery-ui-rails'
# Gems used only for assets and not required
# in production environments by default.
group :assets do
#  gem 'sass-rails',   '~> 3.2.3'
  gem 'sass-rails', git: 'https://github.com/rails/sass-rails.git', branch: '3-2-stable'
  gem 'coffee-rails', '~> 3.2.1'

  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  # gem 'therubyracer', :platforms => :ruby

  gem 'uglifier', '>= 1.0.3'
end

gem 'fancy-buttons'
gem 'jquery-rails'

gem 'forem', :git => "git://github.com/radar/forem.git"
gem 'kaminari'
```

**Comment by parndt** [comment]
I can at least reproduce this now. The downside is it's blocking me from working so I guess I'll look into it. :)

**Comment by boatmon0** [comment]
When testing on another machine running rails "g forem:install" it complains of a problem with the javascript engine.  Might be related, and then again might be a coincidence.

**Comment by parndt** [comment]
Nah you probably just don't have a JS runtime installed on that machine. See ExecJS docs.

**Comment by parndt** [comment]
I think I caused this in f797f289b1e578c0c0163285aa8dc76a88ae26ac

**Comment by parndt** [comment]
@boatmon0 @nazrulcse please run `bundle update --source forem`

**Comment by boatmon0** [comment]
All is very good!  Thank you so much.
