### ISSUE TITLE
Forem Won't Deploy to Heroku – undefined method `path' for nil:NilClass

### ISSUE THREAD

**Issue by austencollins** [rubysherpas/forem#437]
Hello, 

There is a Closed Issue with respects to this error, yet after trying all of the user-submitted solutions, I still cannot get my Forem app to deploy to Heroku.  Is there consensus on how to handle this problem from the developers?

Running: rake assets:precompile
       rake aborted!
       undefined method `path' for nil:NilClass
       (in /tmp/build_2cvaljgexb0i5/vendor/bundle/ruby/1.9.1/bundler/gems/forem-b44bd7374441/app/assets/javascripts/forem.js.erb)

**Comment by radar** [comment]
Hey @ac360, I take it this is the same issue as you stated on #320?

**Comment by caseydierking** [comment]
Is this still on the radar? I have been running into this issue all day long today and I can't figure it out. No matter what I do, I get

 undefined method `path' for nil:NilClass
       (in /tmp/build_2tohubvkc1ofw/vendor/bundle/ruby/2.0.0/bundler/gems/forem-dd93de69b820/app/assets/javascripts/forem.js.erb)

whenever trying to deploy to heroku.

**Comment by parndt** [comment]
Is that the entire stack trace? Have you done anything custom? Is initialize_on_precompile set to true?

**Comment by radar** [comment]
Yes please give me access and I will try to fix it. My email is radarlistener@gmail.com

**Comment by caseydierking** [comment]
Radar, I gave you access on heroku. Also, here is the github for the site. https://github.com/MisterOptimist/timesheet_app

I have

``` ruby
config.assets.initialize_on_precompile = false
```

in my /application.rb file.

the full stack trace is this.

```
-----> Preparing app for Rails asset pipeline
       Running: rake assets:precompile
       rake aborted!
       undefined method `path' for nil:NilClass
       (in /tmp/build_1pltvxkbuvdq9/vendor/bundle/ruby/2.0.0/bundler/gems/forem-dd93de69b820/app/assets/javascripts/forem.js.erb)
       /tmp/build_1pltvxkbuvdq9/vendor/bundle/ruby/2.0.0/bundler/gems/forem-dd93de69b820/lib/forem.rb:22:in `base_path'
       /tmp/build_1pltvxkbuvdq9/vendor/bundle/ruby/2.0.0/bundler/gems/forem-dd93de69b820/app/assets/javascripts/forem.js.erb:4:in `block in singleton class'
       /tmp/build_1pltvxkbuvdq9/vendor/bundle/ruby/2.0.0/bundler/gems/forem-dd93de69b820/app/assets/javascripts/forem.js.erb:-5:in `instance_eval'
       /tmp/build_1pltvxkbuvdq9/vendor/bundle/ruby/2.0.0/bundler/gems/forem-dd93de69b820/app/assets/javascripts/forem.js.erb:-5:in `singleton class'
       /tmp/build_1pltvxkbuvdq9/vendor/bundle/ruby/2.0.0/bundler/gems/forem-dd93de69b820/app/assets/javascripts/forem.js.erb:-7:in `__tilt_70253086580360'
       /tmp/build_1pltvxkbuvdq9/vendor/bundle/ruby/2.0.0/gems/tilt-1.4.1/lib/tilt/template.rb:170:in `call'
       /tmp/build_1pltvxkbuvdq9/vendor/bundle/ruby/2.0.0/gems/tilt-1.4.1/lib/tilt/template.rb:170:in `evaluate'
       /tmp/build_1pltvxkbuvdq9/vendor/bundle/ruby/2.0.0/gems/tilt-1.4.1/lib/tilt/template.rb:103:in `render'
       /tmp/build_1pltvxkbuvdq9/vendor/bundle/ruby/2.0.0/gems/sprockets-2.2.2/lib/sprockets/context.rb:193:in `block in evaluate'
       /tmp/build_1pltvxkbuvdq9/vendor/bundle/ruby/2.0.0/gems/sprockets-2.2.2/lib/sprockets/context.rb:190:in `each'
       /tmp/build_1pltvxkbuvdq9/vendor/bundle/ruby/2.0.0/gems/sprockets-2.2.2/lib/sprockets/context.rb:190:in `evaluate'
       /tmp/build_1pltvxkbuvdq9/vendor/bundle/ruby/2.0.0/gems/sprockets-2.2.2/lib/sprockets/processed_asset.rb:12:in `initialize'
       /tmp/build_1pltvxkbuvdq9/vendor/bundle/ruby/2.0.0/gems/sprockets-2.2.2/lib/sprockets/base.rb:249:in `new'
       /tmp/build_1pltvxkbuvdq9/vendor/bundle/ruby/2.0.0/gems/sprockets-2.2.2/lib/sprockets/base.rb:249:in `block in build_asset'
       /tmp/build_1pltvxkbuvdq9/vendor/bundle/ruby/2.0.0/gems/sprockets-2.2.2/lib/sprockets/base.rb:270:in `circular_call_protection'
       /tmp/build_1pltvxkbuvdq9/vendor/bundle/ruby/2.0.0/gems/sprockets-2.2.2/lib/sprockets/base.rb:248:in `build_asset'
       /tmp/build_1pltvxkbuvdq9/vendor/bundle/ruby/2.0.0/gems/sprockets-2.2.2/lib/sprockets/index.rb:93:in `block in build_asset'
       /tmp/build_1pltvxkbuvdq9/vendor/bundle/ruby/2.0.0/gems/sprockets-2.2.2/lib/sprockets/caching.rb:19:in `cache_asset'
       /tmp/build_1pltvxkbuvdq9/vendor/bundle/ruby/2.0.0/gems/sprockets-2.2.2/lib/sprockets/index.rb:92:in `build_asset'
       /tmp/build_1pltvxkbuvdq9/vendor/bundle/ruby/2.0.0/gems/sprockets-2.2.2/lib/sprockets/base.rb:169:in `find_asset'
       /tmp/build_1pltvxkbuvdq9/vendor/bundle/ruby/2.0.0/gems/sprockets-2.2.2/lib/sprockets/index.rb:60:in `find_asset'
       /tmp/build_1pltvxkbuvdq9/vendor/bundle/ruby/2.0.0/gems/sprockets-2.2.2/lib/sprockets/processed_asset.rb:111:in `block in resolve_dependencies'
       /tmp/build_1pltvxkbuvdq9/vendor/bundle/ruby/2.0.0/gems/sprockets-2.2.2/lib/sprockets/processed_asset.rb:105:in `each'
       /tmp/build_1pltvxkbuvdq9/vendor/bundle/ruby/2.0.0/gems/sprockets-2.2.2/lib/sprockets/processed_asset.rb:105:in `resolve_dependencies'
       /tmp/build_1pltvxkbuvdq9/vendor/bundle/ruby/2.0.0/gems/sprockets-2.2.2/lib/sprockets/processed_asset.rb:97:in `build_required_assets'
       /tmp/build_1pltvxkbuvdq9/vendor/bundle/ruby/2.0.0/gems/sprockets-2.2.2/lib/sprockets/processed_asset.rb:16:in `initialize'
       /tmp/build_1pltvxkbuvdq9/vendor/bundle/ruby/2.0.0/gems/sprockets-2.2.2/lib/sprockets/base.rb:249:in `new'
       /tmp/build_1pltvxkbuvdq9/vendor/bundle/ruby/2.0.0/gems/sprockets-2.2.2/lib/sprockets/base.rb:249:in `block in build_asset'
       /tmp/build_1pltvxkbuvdq9/vendor/bundle/ruby/2.0.0/gems/sprockets-2.2.2/lib/sprockets/base.rb:270:in `circular_call_protection'
       /tmp/build_1pltvxkbuvdq9/vendor/bundle/ruby/2.0.0/gems/sprockets-2.2.2/lib/sprockets/base.rb:248:in `build_asset'
       /tmp/build_1pltvxkbuvdq9/vendor/bundle/ruby/2.0.0/gems/sprockets-2.2.2/lib/sprockets/index.rb:93:in `block in build_asset'
       /tmp/build_1pltvxkbuvdq9/vendor/bundle/ruby/2.0.0/gems/sprockets-2.2.2/lib/sprockets/caching.rb:19:in `cache_asset'
       /tmp/build_1pltvxkbuvdq9/vendor/bundle/ruby/2.0.0/gems/sprockets-2.2.2/lib/sprockets/index.rb:92:in `build_asset'
       /tmp/build_1pltvxkbuvdq9/vendor/bundle/ruby/2.0.0/gems/sprockets-2.2.2/lib/sprockets/base.rb:169:in `find_asset'
       /tmp/build_1pltvxkbuvdq9/vendor/bundle/ruby/2.0.0/gems/sprockets-2.2.2/lib/sprockets/index.rb:60:in `find_asset'
       /tmp/build_1pltvxkbuvdq9/vendor/bundle/ruby/2.0.0/gems/sprockets-2.2.2/lib/sprockets/bundled_asset.rb:16:in `initialize'
       /tmp/build_1pltvxkbuvdq9/vendor/bundle/ruby/2.0.0/gems/sprockets-2.2.2/lib/sprockets/base.rb:252:in `new'
       /tmp/build_1pltvxkbuvdq9/vendor/bundle/ruby/2.0.0/gems/sprockets-2.2.2/lib/sprockets/base.rb:252:in `build_asset'
       /tmp/build_1pltvxkbuvdq9/vendor/bundle/ruby/2.0.0/gems/sprockets-2.2.2/lib/sprockets/index.rb:93:in `block in build_asset'
       /tmp/build_1pltvxkbuvdq9/vendor/bundle/ruby/2.0.0/gems/sprockets-2.2.2/lib/sprockets/caching.rb:19:in `cache_asset'
       /tmp/build_1pltvxkbuvdq9/vendor/bundle/ruby/2.0.0/gems/sprockets-2.2.2/lib/sprockets/index.rb:92:in `build_asset'
       /tmp/build_1pltvxkbuvdq9/vendor/bundle/ruby/2.0.0/gems/sprockets-2.2.2/lib/sprockets/base.rb:169:in `find_asset'
       /tmp/build_1pltvxkbuvdq9/vendor/bundle/ruby/2.0.0/gems/sprockets-2.2.2/lib/sprockets/index.rb:60:in `find_asset'
       /tmp/build_1pltvxkbuvdq9/vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.13/lib/sprockets/static_compiler.rb:19:in `block in compile'
       /tmp/build_1pltvxkbuvdq9/vendor/bundle/ruby/2.0.0/gems/sprockets-2.2.2/lib/sprockets/base.rb:219:in `block in each_logical_path'
       /tmp/build_1pltvxkbuvdq9/vendor/bundle/ruby/2.0.0/gems/sprockets-2.2.2/lib/sprockets/base.rb:206:in `block (2 levels) in each_file'
       /tmp/build_1pltvxkbuvdq9/vendor/bundle/ruby/2.0.0/gems/sprockets-2.2.2/lib/sprockets/base.rb:196:in `each'
       /tmp/build_1pltvxkbuvdq9/vendor/bundle/ruby/2.0.0/gems/sprockets-2.2.2/lib/sprockets/base.rb:196:in `each_entry'
       /tmp/build_1pltvxkbuvdq9/vendor/bundle/ruby/2.0.0/gems/sprockets-2.2.2/lib/sprockets/base.rb:204:in `block in each_file'
       /tmp/build_1pltvxkbuvdq9/vendor/bundle/ruby/2.0.0/gems/sprockets-2.2.2/lib/sprockets/base.rb:203:in `each'
       /tmp/build_1pltvxkbuvdq9/vendor/bundle/ruby/2.0.0/gems/sprockets-2.2.2/lib/sprockets/base.rb:203:in `each_file'
       /tmp/build_1pltvxkbuvdq9/vendor/bundle/ruby/2.0.0/gems/sprockets-2.2.2/lib/sprockets/base.rb:217:in `each_logical_path'
       /tmp/build_1pltvxkbuvdq9/vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.13/lib/sprockets/static_compiler.rb:18:in `compile'
       /tmp/build_1pltvxkbuvdq9/vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.13/lib/sprockets/assets.rake:56:in `internal_precompile'
       /tmp/build_1pltvxkbuvdq9/vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.13/lib/sprockets/assets.rake:70:in `block (3 levels) in <top (required)>'
       /tmp/build_1pltvxkbuvdq9/vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.13/lib/sprockets/assets.rake:60:in `block (3 levels) in <top (required)>'
       /tmp/build_1pltvxkbuvdq9/vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.13/lib/sprockets/assets.rake:23:in `invoke_or_reboot_rake_task'
       /tmp/build_1pltvxkbuvdq9/vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.13/lib/sprockets/assets.rake:29:in `block (2 levels) in <top (required)>'
       Tasks: TOP => assets:precompile:primary
```

**Comment by parndt** [comment]
Set initialize_on_precompile to true

**Comment by parndt** [comment]
And then enable [user-env-compile](https://devcenter.heroku.com/articles/labs-user-env-compile)

**Comment by radar** [comment]
@MisterOptimist I am unable to access that application on Heroku. I don't see it in my list of applications when I am signed in to Heroku, and I am unable to push to that Git repo. Could you please double check that I have permission to access that?

Thank you.

**Comment by caseydierking** [comment]
I did what @parndt recommended and it seems to be working. It kinda feels like a hack though to me. I wish I didn't have to precompile it everytime I sent it up to heroku.

However, I just checked and you do have access. Feel free to upload the code you have. I wouldn't mind seeing how you fixed it. Thanks Radar!

**Comment by caseydierking** [comment]
That, and my javascript datepicker doesn't work now with the precompile.
but thats not a forem issue. :)

Once again thank you guys for your help. I'm still learning rails.

**Comment by radar** [comment]
I have removed that bullshit hackery to do with the member autocomplete and have improved UI in the admin backend very slightly. You should no longer have to set `initialize_on_precompile` to false. Please remove that setting from `config/environments/production.rb` and let me know how a deploy without it goes.

Thanks!

**Comment by caseydierking** [comment]
Could you push the code you deployed to heroku to github for me? I'm having issues with getting mine to work.

I think I might have borked something in the midst of trying to get it to deploy correctly before.

EDIT: Scratch that Radar. Don't do this. I fixed the issue. Thanks for your help!

**Comment by radar** [comment]
@MisterOptimist All good :) The code I have deployed is available at https://github.com/radar/forem.heroku.com for future reference.
