### ISSUE TITLE
Error when installing and further finders error

### ISSUE THREAD

**Issue by link-er** [rubysherpas/forem#470]
Hello!
I'm trying to use rails4 branch. I installed gem and run install generator. Here what I got:

``` bash
rails g forem:install
I, [2013-09-03T15:29:38.358409 #1802]  INFO -- : ** [Raven] Raven 0.6.0 ready to catch errors
Copying over Forem migrations...
What is your user class called? [User] User
What is the current_user helper called in your app? [current_user] current_user
Defining forem_user method inside ApplicationController...
      insert  app/controllers/application_controller.rb
Adding forem initializer (config/initializers/forem.rb)...
      create  config/initializers/forem.rb
Running rake db:migrate
Creating default forum and topic
/home/lina/.rvm/gems/ruby-2.0.0-p195/gems/activemodel-4.0.0/lib/active_model/attribute_methods.rb:436:in `method_missing': undefined method `forem_moderate_posts?' for #<User:0x00000006dd6b60> (NoMethodError)
    from /home/lina/.rvm/gems/ruby-2.0.0-p195/gems/activerecord-4.0.0/lib/active_record/attribute_methods.rb:131:in `method_missing'
```

I thought that it's not very critical for engine working, so I continued, added route and started application. But then, when I tried to get to default forum's page, I got next error:

```
ActiveRecord::RecordNotFound in Forem::ForumsController#show
Couldn't find Forem::Forum with id=default
```

The same with categories.
Is these problems are bugs or am I doing something wrong?

**Comment by parndt** [comment]
Likely bugs.. the error about not being able to find with id=default is likely FriendlyId's API change.

**Comment by link-er** [comment]
adding  `:find_by => :slug` in `load_and_authorize_resource :class => 'Forem::Forum', :only => :show`
 in controller cures the problem (the same in categories controller)
shall I make pull request or you can help?

**Comment by link-er** [comment]
Error on install seems to be happened because nothing was wrote to my User model
As I can see in lib/forem.rb file, there is a method for decorating model, but... smth went wrong

P.S. can you please tell me what else has to be done on generator install, maybe there is anything else missing

**Comment by kekiefer** [comment]
Regarding the id=default bug here, you should use nukturnal/cancan, which fixes the friendly_id 5 issue as @parndt mentioned. You could also fix the issue by modifying the forem model finders (https://github.com/kekiefer/forem/commit/c7717ffab3bb6a8a654c27adfc4f8bb22bea24d7).

**Comment by Senjai** [comment]
Following Ryan's multitenancy book, I also get this error message trying to follow his book.

```
➜  hosted_forums git:(master) rails g forem:install
Copying over Forem migrations...
What is your user class called? [User] Subscribem::User
What is the current_user helper called in your app? [current_user] 
Defining forem_user method inside ApplicationController...
      insert  app/controllers/application_controller.rb
Adding forem initializer (config/initializers/forem.rb)...
      create  config/initializers/forem.rb
Running rake db:migrate
Creating default forum and topic
/home/richard/.rvm/gems/ruby-2.0.0-p247@rails4/gems/activemodel-4.0.0/lib/active_model/attribute_methods.rb:436:in `method_missing': undefined method `forem_moderate_posts?' for #<Subscribem::User:0x000000043ec070> (NoMethodError)
        from /home/richard/.rvm/gems/ruby-2.0.0-p247@rails4/gems/activerecord-4.0.0/lib/active_record/attribute_methods.rb:131:in `method_missing'
        from /home/richard/.rvm/gems/ruby-2.0.0-p247@rails4/bundler/gems/forem-f34fb3d65583/app/models/forem/post.rb:112:in `skip_pending_review'
        from /home/richard/.rvm/gems/ruby-2.0.0-p247@rails4/gems/activesupport-4.0.0/lib/active_support/callbacks.rb:387:in `_run__4601936645212624803__create__callbacks'
        from /home/richard/.rvm/gems/ruby-2.0.0-p247@rails4/gems/activesupport-4.0.0/lib/active_support/callbacks.rb:80:in `run_callbacks'
        from /home/richard/.rvm/gems/ruby-2.0.0-p247@rails4/gems/activerecord-4.0.0/lib/active_record/callbacks.rb:303:in `create_record'
        from /home/richard/.rvm/gems/ruby-2.0.0-p247@rails4/gems/activerecord-4.0.0/lib/active_record/timestamp.rb:57:in `create_record'
        from /home/richard/.rvm/gems/ruby-2.0.0-p247@rails4/gems/activerecord-4.0.0/lib/active_record/persistence.rb:466:in `create_or_update'
        from /home/richard/.rvm/gems/ruby-2.0.0-p247@rails4/gems/activerecord-4.0.0/lib/active_record/callbacks.rb:299:in `block in create_or_update'
        from /home/richard/.rvm/gems/ruby-2.0.0-p247@rails4/gems/activesupport-4.0.0/lib/active_support/callbacks.rb:413:in `_run__4601936645212624803__save__callbacks'
        from /home/richard/.rvm/gems/ruby-2.0.0-p247@rails4/gems/activesupport-4.0.0/lib/active_support/callbacks.rb:80:in `run_callbacks'
        from /home/richard/.rvm/gems/ruby-2.0.0-p247@rails4/gems/activerecord-4.0.0/lib/active_record/callbacks.rb:299:in `create_or_update'
        from /home/richard/.rvm/gems/ruby-2.0.0-p247@rails4/gems/activerecord-4.0.0/lib/active_record/persistence.rb:106:in `save'
        from /home/richard/.rvm/gems/ruby-2.0.0-p247@rails4/gems/activerecord-4.0.0/lib/active_record/validations.rb:51:in `save'
        from /home/richard/.rvm/gems/ruby-2.0.0-p247@rails4/gems/activerecord-4.0.0/lib/active_record/attribute_methods/dirty.rb:32:in `save'
        from /home/richard/.rvm/gems/ruby-2.0.0-p247@rails4/gems/activerecord-4.0.0/lib/active_record/transactions.rb:270:in `block (2 levels) in save'
        from /home/richard/.rvm/gems/ruby-2.0.0-p247@rails4/gems/activerecord-4.0.0/lib/active_record/transactions.rb:326:in `block in with_transaction_returning_status'
        from /home/richard/.rvm/gems/ruby-2.0.0-p247@rails4/gems/activerecord-4.0.0/lib/active_record/connection_adapters/abstract/database_statements.rb:200:in `transaction'
        from /home/richard/.rvm/gems/ruby-2.0.0-p247@rails4/gems/activerecord-4.0.0/lib/active_record/transactions.rb:209:in `transaction'
        from /home/richard/.rvm/gems/ruby-2.0.0-p247@rails4/gems/activerecord-4.0.0/lib/active_record/transactions.rb:323:in `with_transaction_returning_status'
        from /home/richard/.rvm/gems/ruby-2.0.0-p247@rails4/gems/activerecord-4.0.0/lib/active_record/transactions.rb:270:in `block in save'
        from /home/richard/.rvm/gems/ruby-2.0.0-p247@rails4/gems/activerecord-4.0.0/lib/active_record/transactions.rb:281:in `rollback_active_record_state!'
        from /home/richard/.rvm/gems/ruby-2.0.0-p247@rails4/gems/activerecord-4.0.0/lib/active_record/transactions.rb:269:in `save'
        from /home/richard/.rvm/gems/ruby-2.0.0-p247@rails4/gems/activerecord-4.0.0/lib/active_record/associations/has_many_association.rb:39:in `insert_record'
        from /home/richard/.rvm/gems/ruby-2.0.0-p247@rails4/gems/activerecord-4.0.0/lib/active_record/autosave_association.rb:348:in `block in save_collection_association'
        from /home/richard/.rvm/gems/ruby-2.0.0-p247@rails4/gems/activerecord-4.0.0/lib/active_record/autosave_association.rb:339:in `each'
        from /home/richard/.rvm/gems/ruby-2.0.0-p247@rails4/gems/activerecord-4.0.0/lib/active_record/autosave_association.rb:339:in `save_collection_association'
        from /home/richard/.rvm/gems/ruby-2.0.0-p247@rails4/gems/activerecord-4.0.0/lib/active_record/autosave_association.rb:183:in `block in add_autosave_association_callbacks'
        from /home/richard/.rvm/gems/ruby-2.0.0-p247@rails4/gems/activerecord-4.0.0/lib/active_record/autosave_association.rb:153:in `instance_eval'
        from /home/richard/.rvm/gems/ruby-2.0.0-p247@rails4/gems/activerecord-4.0.0/lib/active_record/autosave_association.rb:153:in `block in define_non_cyclic_method'
        from /home/richard/.rvm/gems/ruby-2.0.0-p247@rails4/gems/activesupport-4.0.0/lib/active_support/callbacks.rb:383:in `_run__934894413692714415__create__callbacks'
        from /home/richard/.rvm/gems/ruby-2.0.0-p247@rails4/gems/activesupport-4.0.0/lib/active_support/callbacks.rb:80:in `run_callbacks'
        from /home/richard/.rvm/gems/ruby-2.0.0-p247@rails4/gems/activerecord-4.0.0/lib/active_record/callbacks.rb:303:in `create_record'
        from /home/richard/.rvm/gems/ruby-2.0.0-p247@rails4/gems/activerecord-4.0.0/lib/active_record/timestamp.rb:57:in `create_record'
        from /home/richard/.rvm/gems/ruby-2.0.0-p247@rails4/gems/activerecord-4.0.0/lib/active_record/persistence.rb:466:in `create_or_update'
        from /home/richard/.rvm/gems/ruby-2.0.0-p247@rails4/gems/activerecord-4.0.0/lib/active_record/callbacks.rb:299:in `block in create_or_update'
        from /home/richard/.rvm/gems/ruby-2.0.0-p247@rails4/gems/activesupport-4.0.0/lib/active_support/callbacks.rb:413:in `_run__934894413692714415__save__callbacks'
        from /home/richard/.rvm/gems/ruby-2.0.0-p247@rails4/gems/activesupport-4.0.0/lib/active_support/callbacks.rb:80:in `run_callbacks'
        from /home/richard/.rvm/gems/ruby-2.0.0-p247@rails4/gems/activerecord-4.0.0/lib/active_record/callbacks.rb:299:in `create_or_update'
        from /home/richard/.rvm/gems/ruby-2.0.0-p247@rails4/gems/activerecord-4.0.0/lib/active_record/persistence.rb:128:in `save!'
        from /home/richard/.rvm/gems/ruby-2.0.0-p247@rails4/gems/activerecord-4.0.0/lib/active_record/validations.rb:57:in `save!'
        from /home/richard/.rvm/gems/ruby-2.0.0-p247@rails4/gems/activerecord-4.0.0/lib/active_record/attribute_methods/dirty.rb:41:in `save!'
        from /home/richard/.rvm/gems/ruby-2.0.0-p247@rails4/gems/activerecord-4.0.0/lib/active_record/transactions.rb:275:in `block in save!'
        from /home/richard/.rvm/gems/ruby-2.0.0-p247@rails4/gems/activerecord-4.0.0/lib/active_record/transactions.rb:326:in `block in with_transaction_returning_status'
        from /home/richard/.rvm/gems/ruby-2.0.0-p247@rails4/gems/activerecord-4.0.0/lib/active_record/connection_adapters/abstract/database_statements.rb:202:in `block in transaction'
        from /home/richard/.rvm/gems/ruby-2.0.0-p247@rails4/gems/activerecord-4.0.0/lib/active_record/connection_adapters/abstract/database_statements.rb:210:in `within_new_transaction'
        from /home/richard/.rvm/gems/ruby-2.0.0-p247@rails4/gems/activerecord-4.0.0/lib/active_record/connection_adapters/abstract/database_statements.rb:202:in `transaction'
        from /home/richard/.rvm/gems/ruby-2.0.0-p247@rails4/gems/activerecord-4.0.0/lib/active_record/transactions.rb:209:in `transaction'
        from /home/richard/.rvm/gems/ruby-2.0.0-p247@rails4/gems/activerecord-4.0.0/lib/active_record/transactions.rb:323:in `with_transaction_returning_status'
        from /home/richard/.rvm/gems/ruby-2.0.0-p247@rails4/gems/activerecord-4.0.0/lib/active_record/transactions.rb:275:in `save!'
        from /home/richard/.rvm/gems/ruby-2.0.0-p247@rails4/bundler/gems/forem-f34fb3d65583/db/seeds.rb:17:in `<top (required)>'
        from /home/richard/.rvm/gems/ruby-2.0.0-p247@rails4/gems/activesupport-4.0.0/lib/active_support/dependencies.rb:222:in `load'
        from /home/richard/.rvm/gems/ruby-2.0.0-p247@rails4/gems/activesupport-4.0.0/lib/active_support/dependencies.rb:222:in `block in load'
        from /home/richard/.rvm/gems/ruby-2.0.0-p247@rails4/gems/activesupport-4.0.0/lib/active_support/dependencies.rb:213:in `load_dependency'
        from /home/richard/.rvm/gems/ruby-2.0.0-p247@rails4/gems/activesupport-4.0.0/lib/active_support/dependencies.rb:222:in `load'
        from /home/richard/.rvm/gems/ruby-2.0.0-p247@rails4/gems/railties-4.0.0/lib/rails/engine.rb:540:in `load_seed'
        from /home/richard/.rvm/gems/ruby-2.0.0-p247@rails4/gems/railties-4.0.0/lib/rails/railtie/configurable.rb:30:in `method_missing'
        from /home/richard/.rvm/gems/ruby-2.0.0-p247@rails4/bundler/gems/forem-f34fb3d65583/lib/generators/forem/install_generator.rb:68:in `seed_database'
        from /home/richard/.rvm/gems/ruby-2.0.0-p247@rails4/gems/thor-0.18.1/lib/thor/command.rb:27:in `run'
        from /home/richard/.rvm/gems/ruby-2.0.0-p247@rails4/gems/thor-0.18.1/lib/thor/invocation.rb:120:in `invoke_command'
        from /home/richard/.rvm/gems/ruby-2.0.0-p247@rails4/gems/thor-0.18.1/lib/thor/invocation.rb:127:in `block in invoke_all'
        from /home/richard/.rvm/gems/ruby-2.0.0-p247@rails4/gems/thor-0.18.1/lib/thor/invocation.rb:127:in `each'
        from /home/richard/.rvm/gems/ruby-2.0.0-p247@rails4/gems/thor-0.18.1/lib/thor/invocation.rb:127:in `map'
        from /home/richard/.rvm/gems/ruby-2.0.0-p247@rails4/gems/thor-0.18.1/lib/thor/invocation.rb:127:in `invoke_all'
        from /home/richard/.rvm/gems/ruby-2.0.0-p247@rails4/gems/thor-0.18.1/lib/thor/group.rb:233:in `dispatch'
        from /home/richard/.rvm/gems/ruby-2.0.0-p247@rails4/gems/thor-0.18.1/lib/thor/base.rb:439:in `start'
        from /home/richard/.rvm/gems/ruby-2.0.0-p247@rails4/gems/railties-4.0.0/lib/rails/generators.rb:156:in `invoke'
        from /home/richard/.rvm/gems/ruby-2.0.0-p247@rails4/gems/railties-4.0.0/lib/rails/commands/generate.rb:11:in `<top (required)>'
        from /home/richard/.rvm/gems/ruby-2.0.0-p247@rails4/gems/activesupport-4.0.0/lib/active_support/dependencies.rb:228:in `require'
        from /home/richard/.rvm/gems/ruby-2.0.0-p247@rails4/gems/activesupport-4.0.0/lib/active_support/dependencies.rb:228:in `block in require'
        from /home/richard/.rvm/gems/ruby-2.0.0-p247@rails4/gems/activesupport-4.0.0/lib/active_support/dependencies.rb:213:in `load_dependency'
        from /home/richard/.rvm/gems/ruby-2.0.0-p247@rails4/gems/activesupport-4.0.0/lib/active_support/dependencies.rb:228:in `require'
        from /home/richard/.rvm/gems/ruby-2.0.0-p247@rails4/gems/railties-4.0.0/lib/rails/commands.rb:49:in `<top (required)>'
        from bin/rails:4:in `require'
        from bin/rails:4:in `<main>'
```

**Comment by bobbdelsol** [comment]
I also got the forem_moderate_posts? method not defined error
/Users/bobby/.gem/ruby/2.0.0/gems/activemodel-4.0.2/lib/active_model/attribute_methods.rb:439:in `method_missing': undefined method`forem_moderate_posts?' for #User:0x007f96e654eed8 (NoMethodError)

Second run no-problem,  Things seem to work, so I'm betting an ordering problem in the original migrations set.

**Comment by bobbdelsol** [comment]
I don't see a moderator attribute in User

**Comment by radar** [comment]
The friendly_id bug should be fixed in all branches. Please let me know if it's not fixed in either master or rails4.

As for the `forem_moderate_posts?` issue that @bobbdelsol reported, it is not related to this issue.
