### ISSUE TITLE
Two related (?) issues - undefined method `forem_moderate_posts?; undefined local variable or method `name'

### ISSUE THREAD

**Issue by philiprhoades** [rubysherpas/forem#495]
People,

Firstly, thanks for this software!

I have looked through old issues but can't see this covered:

This: https://github.com/jayshepherd/devise_example

works fine. I then install this: https://github.com/radar/forem

but the first time I run: rails g forem:install

I get:

Running rake db:migrate
/home/phil/.gem/ruby/gems/activemodel-4.0.0/lib/active_model/attribute_methods.rb:436:in `method_missing': undefined method`forem_moderate_posts?' for #<User
:0x00000004e6d698> (NoMethodError)

but when I run it again it appears to finish OK. Logging in as the test user and looking at: /forums

works OK but when I add:

def to_s
  name
end

to the user model at /forums I get:

Showing /home/phil/.gem/ruby/bundler/gems/forem-f34fb3d65583/app/views/forem/forums/_forum.html.erb where line #8 raised:

undefined local variable or method `name' for #User:0x00000003c72f60

Fixes appreciated!

Regards,
Phil.

**Comment by radar** [comment]
Hi @philiprhoades,

Could you please show me the complete output from `rails g forem:install`? I don't see the prompts in the message you posted and I'm interested to see what values you put in for that.

Thanks!

**Comment by philiprhoades** [comment]
radar,

I just used the defaults:

```
[DEVISE] Devise.use_salt_as_remember_token is deprecated and has no effect. Please remove it.
Copying over Forem migrations...
What is your user class called? [User] What is the current_user helper called in your app? [current_user] Defining forem_user method inside ApplicationController...
[1m[32m      insert[0m  app/controllers/application_controller.rb
Adding forem initializer (config/initializers/forem.rb)...
[1m[32m      create[0m  config/initializers/forem.rb
Running rake db:migrate
/home/phil/.gem/ruby/gems/activemodel-4.0.0/lib/active_model/attribute_methods.rb:436:in `method_missing': undefined method `forem_moderate_posts?' for #<User:0x00000004e6d698> (NoMethodError)
    from /home/phil/.gem/ruby/gems/activerecord-4.0.0/lib/active_record/attribute_methods.rb:131:in `method_missing'
    from /home/phil/.gem/ruby/bundler/gems/forem-f34fb3d65583/app/models/forem/post.rb:112:in `skip_pending_review'
    from /home/phil/.gem/ruby/gems/activesupport-4.0.0/lib/active_support/callbacks.rb:387:in `_run__4084960174987532839__create__callbacks'
    from /home/phil/.gem/ruby/gems/activesupport-4.0.0/lib/active_support/callbacks.rb:80:in `run_callbacks'
    from /home/phil/.gem/ruby/gems/activerecord-4.0.0/lib/active_record/callbacks.rb:303:in `create_record'
    from /home/phil/.gem/ruby/gems/activerecord-4.0.0/lib/active_record/timestamp.rb:57:in `create_record'
    from /home/phil/.gem/ruby/gems/activerecord-4.0.0/lib/active_record/persistence.rb:466:in `create_or_update'
    from /home/phil/.gem/ruby/gems/activerecord-4.0.0/lib/active_record/callbacks.rb:299:in `block in create_or_update'
    from /home/phil/.gem/ruby/gems/activesupport-4.0.0/lib/active_support/callbacks.rb:413:in `_run__4084960174987532839__save__callbacks'
    from /home/phil/.gem/ruby/gems/activesupport-4.0.0/lib/active_support/callbacks.rb:80:in `run_callbacks'
    from /home/phil/.gem/ruby/gems/activerecord-4.0.0/lib/active_record/callbacks.rb:299:in `create_or_update'
    from /home/phil/.gem/ruby/gems/activerecord-4.0.0/lib/active_record/persistence.rb:106:in `save'
    from /home/phil/.gem/ruby/gems/activerecord-4.0.0/lib/active_record/validations.rb:51:in `save'
    from /home/phil/.gem/ruby/gems/activerecord-4.0.0/lib/active_record/attribute_methods/dirty.rb:32:in `save'
    from /home/phil/.gem/ruby/gems/activerecord-4.0.0/lib/active_record/transactions.rb:270:in `block (2 levels) in save'
    from /home/phil/.gem/ruby/gems/activerecord-4.0.0/lib/active_record/transactions.rb:326:in `block in with_transaction_returning_status'
    from /home/phil/.gem/ruby/gems/activerecord-4.0.0/lib/active_record/connection_adapters/abstract/database_statements.rb:200:in `transaction'
    from /home/phil/.gem/ruby/gems/activerecord-4.0.0/lib/active_record/transactions.rb:209:in `transaction'
    from /home/phil/.gem/ruby/gems/activerecord-4.0.0/lib/active_record/transactions.rb:323:in `with_transaction_returning_status'
    from /home/phil/.gem/ruby/gems/activerecord-4.0.0/lib/active_record/transactions.rb:270:in `block in save'
    from /home/phil/.gem/ruby/gems/activerecord-4.0.0/lib/active_record/transactions.rb:281:in `rollback_active_record_state!'
    from /home/phil/.gem/ruby/gems/activerecord-4.0.0/lib/active_record/transactions.rb:269:in `save'
    from /home/phil/.gem/ruby/gems/activerecord-4.0.0/lib/active_record/associations/has_many_association.rb:39:in `insert_record'
    from /home/phil/.gem/ruby/gems/activerecord-4.0.0/lib/active_record/autosave_association.rb:348:in `block in save_collection_association'
    from /home/phil/.gem/ruby/gems/activerecord-4.0.0/lib/active_record/autosave_association.rb:339:in `each'
    from /home/phil/.gem/ruby/gems/activerecord-4.0.0/lib/active_record/autosave_association.rb:339:in `save_collection_association'
    from /home/phil/.gem/ruby/gems/activerecord-4.0.0/lib/active_record/autosave_association.rb:183:in `block in add_autosave_association_callbacks'
    from /home/phil/.gem/ruby/gems/activerecord-4.0.0/lib/active_record/autosave_association.rb:153:in `instance_eval'
    from /home/phil/.gem/ruby/gems/activerecord-4.0.0/lib/active_record/autosave_association.rb:153:in `block in define_non_cyclic_method'
    from /home/phil/.gem/ruby/gems/activesupport-4.0.0/lib/active_support/callbacks.rb:383:in `_run__1987470903435521851__create__callbacks'
    from /home/phil/.gem/ruby/gems/activesupport-4.0.0/lib/active_support/callbacks.rb:80:in `run_callbacks'
    from /home/phil/.gem/ruby/gems/activerecord-4.0.0/lib/active_record/callbacks.rb:303:in `create_record'
    from /home/phil/.gem/ruby/gems/activerecord-4.0.0/lib/active_record/timestamp.rb:57:in `create_record'
    from /home/phil/.gem/ruby/gems/activerecord-4.0.0/lib/active_record/persistence.rb:466:in `create_or_update'
    from /home/phil/.gem/ruby/gems/activerecord-4.0.0/lib/active_record/callbacks.rb:299:in `block in create_or_update'
    from /home/phil/.gem/ruby/gems/activesupport-4.0.0/lib/active_support/callbacks.rb:413:in `_run__1987470903435521851__save__callbacks'
    from /home/phil/.gem/ruby/gems/activesupport-4.0.0/lib/active_support/callbacks.rb:80:in `run_callbacks'
    from /home/phil/.gem/ruby/gems/activerecord-4.0.0/lib/active_record/callbacks.rb:299:in `create_or_update'
    from /home/phil/.gem/ruby/gems/activerecord-4.0.0/lib/active_record/persistence.rb:128:in `save!'
    from /home/phil/.gem/ruby/gems/activerecord-4.0.0/lib/active_record/validations.rb:57:in `save!'
    from /home/phil/.gem/ruby/gems/activerecord-4.0.0/lib/active_record/attribute_methods/dirty.rb:41:in `save!'
    from /home/phil/.gem/ruby/gems/activerecord-4.0.0/lib/active_record/transactions.rb:275:in `block in save!'
    from /home/phil/.gem/ruby/gems/activerecord-4.0.0/lib/active_record/transactions.rb:326:in `block in with_transaction_returning_status'
    from /home/phil/.gem/ruby/gems/activerecord-4.0.0/lib/active_record/connection_adapters/abstract/database_statements.rb:202:in `block in transaction'
    from /home/phil/.gem/ruby/gems/activerecord-4.0.0/lib/active_record/connection_adapters/abstract/database_statements.rb:210:in `within_new_transaction'
    from /home/phil/.gem/ruby/gems/activerecord-4.0.0/lib/active_record/connection_adapters/abstract/database_statements.rb:202:in `transaction'
    from /home/phil/.gem/ruby/gems/activerecord-4.0.0/lib/active_record/transactions.rb:209:in `transaction'
    from /home/phil/.gem/ruby/gems/activerecord-4.0.0/lib/active_record/transactions.rb:323:in `with_transaction_returning_status'
    from /home/phil/.gem/ruby/gems/activerecord-4.0.0/lib/active_record/transactions.rb:275:in `save!'
    from /home/phil/.gem/ruby/bundler/gems/forem-f34fb3d65583/db/seeds.rb:17:in `<top (required)>'
    from /home/phil/.gem/ruby/gems/activesupport-4.0.0/lib/active_support/dependencies.rb:222:in `load'
    from /home/phil/.gem/ruby/gems/activesupport-4.0.0/lib/active_support/dependencies.rb:222:in `block in load'
    from /home/phil/.gem/ruby/gems/activesupport-4.0.0/lib/active_support/dependencies.rb:213:in `load_dependency'
    from /home/phil/.gem/ruby/gems/activesupport-4.0.0/lib/active_support/dependencies.rb:222:in `load'
    from /home/phil/.gem/ruby/gems/railties-4.0.0/lib/rails/engine.rb:540:in `load_seed'
    from /home/phil/.gem/ruby/gems/railties-4.0.0/lib/rails/railtie/configurable.rb:30:in `method_missing'
    from /home/phil/.gem/ruby/bundler/gems/forem-f34fb3d65583/lib/generators/forem/install_generator.rb:68:in `seed_database'
    from /home/phil/.gem/ruby/gems/thor-0.18.1/lib/thor/command.rb:27:in `run'
    from /home/phil/.gem/ruby/gems/thor-0.18.1/lib/thor/invocation.rb:120:in `invoke_command'
    from /home/phil/.gem/ruby/gems/thor-0.18.1/lib/thor/invocation.rb:127:in `block in invoke_all'
    from /home/phil/.gem/ruby/gems/thor-0.18.1/lib/thor/invocation.rb:127:in `each'
    from /home/phil/.gem/ruby/gems/thor-0.18.1/lib/thor/invocation.rb:127:in `map'
    from /home/phil/.gem/ruby/gems/thor-0.18.1/lib/thor/invocation.rb:127:in `invoke_all'
    from /home/phil/.gem/ruby/gems/thor-0.18.1/lib/thor/group.rb:233:in `dispatch'
    from /home/phil/.gem/ruby/gems/thor-0.18.1/lib/thor/base.rb:439:in `start'
    from /home/phil/.gem/ruby/gems/railties-4.0.0/lib/rails/generators.rb:156:in `invoke'
    from /home/phil/.gem/ruby/gems/railties-4.0.0/lib/rails/commands/generate.rb:11:in `<top (required)>'
    from /home/phil/.gem/ruby/gems/activesupport-4.0.0/lib/active_support/dependencies.rb:228:in `require'
    from /home/phil/.gem/ruby/gems/activesupport-4.0.0/lib/active_support/dependencies.rb:228:in `block in require'
    from /home/phil/.gem/ruby/gems/activesupport-4.0.0/lib/active_support/dependencies.rb:213:in `load_dependency'
    from /home/phil/.gem/ruby/gems/activesupport-4.0.0/lib/active_support/dependencies.rb:228:in `require'
    from /home/phil/.gem/ruby/gems/railties-4.0.0/lib/rails/commands.rb:49:in `<top (required)>'
    from bin/rails:4:in `require'
    from bin/rails:4:in `<main>'
Creating default forum and topic
```

Thanks!
Phil.

**Comment by radar** [comment]
Interesting... Do you have this application on GitHub somewhere that I can access it?

**Comment by philiprhoades** [comment]
No, just on my laptop - should I put it on GitHub or tgz it and put it somewhere?

Thanks,
Phil.

**Comment by mijoharas** [comment]
I had a similar issue: 

```
➜ rails g forem:install
Copying over Forem migrations...
What is your user class called? [User] User
What is the current_user helper called in your app? [current_user] current_user
Defining forem_user method inside ApplicationController...
      insert  app/controllers/application_controller.rb
Adding forem initializer (config/initializers/forem.rb)...
      create  config/initializers/forem.rb
Running rake db:migrate
Creating default forum and topic
/home/michael/.rvm/gems/ruby-2.0.0-p247/gems/activemodel-4.0.1/lib/active_model/attribute_methods.rb:439:in `method_missing': undefined method `forem_moderate_posts?' for #<User:0x000000069c9c20> (NoMethodError)
    from /home/michael/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-4.0.1/lib/active_record/attribute_methods.rb:155:in `method_missing'
    from /home/michael/.rvm/gems/ruby-2.0.0-p247/bundler/gems/forem-2ef06ad0521d/app/models/forem/post.rb:112:in `skip_pending_review'
    from /home/michael/.rvm/gems/ruby-2.0.0-p247/gems/activesupport-4.0.1/lib/active_support/callbacks.rb:387:in `_run__3413286596083778058__create__callbacks'
    from /home/michael/.rvm/gems/ruby-2.0.0-p247/gems/activesupport-4.0.1/lib/active_support/callbacks.rb:80:in `run_callbacks'
    from /home/michael/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-4.0.1/lib/active_record/callbacks.rb:306:in `create_record'
    from /home/michael/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-4.0.1/lib/active_record/timestamp.rb:57:in `create_record'
    from /home/michael/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-4.0.1/lib/active_record/persistence.rb:477:in `create_or_update'
    from /home/michael/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-4.0.1/lib/active_record/callbacks.rb:302:in `block in create_or_update'
    from /home/michael/.rvm/gems/ruby-2.0.0-p247/gems/activesupport-4.0.1/lib/active_support/callbacks.rb:413:in `_run__3413286596083778058__save__callbacks'
    from /home/michael/.rvm/gems/ruby-2.0.0-p247/gems/activesupport-4.0.1/lib/active_support/callbacks.rb:80:in `run_callbacks'
    from /home/michael/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-4.0.1/lib/active_record/callbacks.rb:302:in `create_or_update'
    from /home/michael/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-4.0.1/lib/active_record/persistence.rb:106:in `save'
    from /home/michael/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-4.0.1/lib/active_record/validations.rb:51:in `save'
    from /home/michael/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-4.0.1/lib/active_record/attribute_methods/dirty.rb:32:in `save'
    from /home/michael/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-4.0.1/lib/active_record/transactions.rb:270:in `block (2 levels) in save'
    from /home/michael/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-4.0.1/lib/active_record/transactions.rb:326:in `block in with_transaction_returning_status'
    from /home/michael/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-4.0.1/lib/active_record/connection_adapters/abstract/database_statements.rb:200:in `transaction'
    from /home/michael/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-4.0.1/lib/active_record/transactions.rb:209:in `transaction'
    from /home/michael/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-4.0.1/lib/active_record/transactions.rb:323:in `with_transaction_returning_status'
    from /home/michael/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-4.0.1/lib/active_record/transactions.rb:270:in `block in save'
    from /home/michael/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-4.0.1/lib/active_record/transactions.rb:281:in `rollback_active_record_state!'
    from /home/michael/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-4.0.1/lib/active_record/transactions.rb:269:in `save'
    from /home/michael/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-4.0.1/lib/active_record/associations/has_many_association.rb:40:in `insert_record'
    from /home/michael/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-4.0.1/lib/active_record/autosave_association.rb:352:in `block in save_collection_association'
    from /home/michael/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-4.0.1/lib/active_record/autosave_association.rb:345:in `each'
    from /home/michael/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-4.0.1/lib/active_record/autosave_association.rb:345:in `save_collection_association'
    from /home/michael/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-4.0.1/lib/active_record/autosave_association.rb:183:in `block in add_autosave_association_callbacks'
    from /home/michael/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-4.0.1/lib/active_record/autosave_association.rb:153:in `instance_eval'
    from /home/michael/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-4.0.1/lib/active_record/autosave_association.rb:153:in `block in define_non_cyclic_method'
    from /home/michael/.rvm/gems/ruby-2.0.0-p247/gems/activesupport-4.0.1/lib/active_support/callbacks.rb:383:in `_run__1380524507118476183__create__callbacks'
    from /home/michael/.rvm/gems/ruby-2.0.0-p247/gems/activesupport-4.0.1/lib/active_support/callbacks.rb:80:in `run_callbacks'
    from /home/michael/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-4.0.1/lib/active_record/callbacks.rb:306:in `create_record'
    from /home/michael/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-4.0.1/lib/active_record/timestamp.rb:57:in `create_record'
    from /home/michael/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-4.0.1/lib/active_record/persistence.rb:477:in `create_or_update'
    from /home/michael/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-4.0.1/lib/active_record/callbacks.rb:302:in `block in create_or_update'
    from /home/michael/.rvm/gems/ruby-2.0.0-p247/gems/activesupport-4.0.1/lib/active_support/callbacks.rb:413:in `_run__1380524507118476183__save__callbacks'
    from /home/michael/.rvm/gems/ruby-2.0.0-p247/gems/activesupport-4.0.1/lib/active_support/callbacks.rb:80:in `run_callbacks'
    from /home/michael/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-4.0.1/lib/active_record/callbacks.rb:302:in `create_or_update'
    from /home/michael/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-4.0.1/lib/active_record/persistence.rb:128:in `save!'
    from /home/michael/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-4.0.1/lib/active_record/validations.rb:57:in `save!'
    from /home/michael/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-4.0.1/lib/active_record/attribute_methods/dirty.rb:41:in `save!'
    from /home/michael/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-4.0.1/lib/active_record/transactions.rb:275:in `block in save!'
    from /home/michael/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-4.0.1/lib/active_record/transactions.rb:326:in `block in with_transaction_returning_status'
    from /home/michael/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-4.0.1/lib/active_record/connection_adapters/abstract/database_statements.rb:202:in `block in transaction'
    from /home/michael/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-4.0.1/lib/active_record/connection_adapters/abstract/database_statements.rb:210:in `within_new_transaction'
    from /home/michael/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-4.0.1/lib/active_record/connection_adapters/abstract/database_statements.rb:202:in `transaction'
    from /home/michael/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-4.0.1/lib/active_record/transactions.rb:209:in `transaction'
    from /home/michael/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-4.0.1/lib/active_record/transactions.rb:323:in `with_transaction_returning_status'
    from /home/michael/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-4.0.1/lib/active_record/transactions.rb:275:in `save!'
    from /home/michael/.rvm/gems/ruby-2.0.0-p247/bundler/gems/forem-2ef06ad0521d/db/seeds.rb:17:in `<top (required)>'
    from /home/michael/.rvm/gems/ruby-2.0.0-p247/gems/activesupport-4.0.1/lib/active_support/dependencies.rb:223:in `load'
    from /home/michael/.rvm/gems/ruby-2.0.0-p247/gems/activesupport-4.0.1/lib/active_support/dependencies.rb:223:in `block in load'
    from /home/michael/.rvm/gems/ruby-2.0.0-p247/gems/activesupport-4.0.1/lib/active_support/dependencies.rb:214:in `load_dependency'
    from /home/michael/.rvm/gems/ruby-2.0.0-p247/gems/activesupport-4.0.1/lib/active_support/dependencies.rb:223:in `load'
    from /home/michael/.rvm/gems/ruby-2.0.0-p247/gems/railties-4.0.1/lib/rails/engine.rb:540:in `load_seed'
    from /home/michael/.rvm/gems/ruby-2.0.0-p247/gems/railties-4.0.1/lib/rails/railtie/configurable.rb:30:in `method_missing'
    from /home/michael/.rvm/gems/ruby-2.0.0-p247/bundler/gems/forem-2ef06ad0521d/lib/generators/forem/install_generator.rb:68:in `seed_database'
    from /home/michael/.rvm/gems/ruby-2.0.0-p247/gems/thor-0.18.1/lib/thor/command.rb:27:in `run'
    from /home/michael/.rvm/gems/ruby-2.0.0-p247/gems/thor-0.18.1/lib/thor/invocation.rb:120:in `invoke_command'
    from /home/michael/.rvm/gems/ruby-2.0.0-p247/gems/thor-0.18.1/lib/thor/invocation.rb:127:in `block in invoke_all'
    from /home/michael/.rvm/gems/ruby-2.0.0-p247/gems/thor-0.18.1/lib/thor/invocation.rb:127:in `each'
    from /home/michael/.rvm/gems/ruby-2.0.0-p247/gems/thor-0.18.1/lib/thor/invocation.rb:127:in `map'
    from /home/michael/.rvm/gems/ruby-2.0.0-p247/gems/thor-0.18.1/lib/thor/invocation.rb:127:in `invoke_all'
    from /home/michael/.rvm/gems/ruby-2.0.0-p247/gems/thor-0.18.1/lib/thor/group.rb:233:in `dispatch'
    from /home/michael/.rvm/gems/ruby-2.0.0-p247/gems/thor-0.18.1/lib/thor/base.rb:439:in `start'
    from /home/michael/.rvm/gems/ruby-2.0.0-p247/gems/railties-4.0.1/lib/rails/generators.rb:156:in `invoke'
    from /home/michael/.rvm/gems/ruby-2.0.0-p247/gems/railties-4.0.1/lib/rails/commands/generate.rb:11:in `<top (required)>'
    from /home/michael/.rvm/gems/ruby-2.0.0-p247/gems/activesupport-4.0.1/lib/active_support/dependencies.rb:229:in `require'
    from /home/michael/.rvm/gems/ruby-2.0.0-p247/gems/activesupport-4.0.1/lib/active_support/dependencies.rb:229:in `block in require'
    from /home/michael/.rvm/gems/ruby-2.0.0-p247/gems/activesupport-4.0.1/lib/active_support/dependencies.rb:214:in `load_dependency'
    from /home/michael/.rvm/gems/ruby-2.0.0-p247/gems/activesupport-4.0.1/lib/active_support/dependencies.rb:229:in `require'
    from /home/michael/.rvm/gems/ruby-2.0.0-p247/gems/railties-4.0.1/lib/rails/commands.rb:48:in `<top (required)>'
    from bin/rails:4:in `require'
    from bin/rails:4:in `<main>'
➜  rails g forem:install
Copying over Forem migrations...
What is your user class called? [User] User
What is the current_user helper called in your app? [current_user] current_user
Defining forem_user method inside ApplicationController...
      insert  app/controllers/application_controller.rb
Skipping config/initializers/forem.rb creation, as file already exists!
Running rake db:migrate
Creating default forum and topic
Mounting Forem::Engine at "/forums" in config/routes.rb...
      insert  config/routes.rb


*****************************************************
Done! Forem has been successfully installed. Yaaaaay!

Here's what happened:

1) Forem's migrations were copied over into db/migrate.

2) We created a new migration called AddForemAdminToTable.
   This creates a new field called "forem_admin" on your User model's table.

3) A new method called `forem_user` was inserted into your ApplicationController.
   This lets Forem know what the current user of your application is.

4) A new file was created at config/initializers/forem.rb
   This is where you put Forem's configuration settings.

5) `rake db:migrate` was run, running all the migrations against your database.

6) Seed forum and topic were loaded into your database.

7) The engine was mounted in your config/routes.rb file using this line:

   mount Forem::Engine, :at => "/forums"

   If you want to change where the forums are located, just change the "/forums" path at the end of this line to whatever you want.

And finally:

8) We told you that Forem has been successfully installed and walked you through the steps.
We have detected you're not using Devise (which is OK with us, really!), so there's one extra step you'll need to do.

   You'll need to define a "sign_in_path" method for Forem to use that points to the sign in path for your application. You can set Forem.sign_in_path to a String inside config/initializers/forem.rb to do this, or you can define it in your config/routes.rb file with a line like this:

          get '/users/sign_in', :to => "users#sign_in"

   Either way, Forem needs one of these two things in order to work properly. Please define them!
If you have any questions, comments or issues, please post them on our issues page: http://github.com/radar/forem/issues.

Thanks for using Forem!
```

**Comment by bodrovis** [comment]
`undefined local variable or method 'name'`  raises because Devise creates User model with no `name` column. I got the same problem and just added this column to User model. I think that forem documentation should be slightly changed to mention this fact. Of course, users should be given an option to enter their name during registration and after they sign in.

**Comment by radar** [comment]
I don't understand what's causing this undefined method `forem_moderate_posts?`...

Does somebody have a Gemfile for an app that I can use to reproduce this issue?

**Comment by joelhooks** [comment]
I'm just adding this here because it shows up when you search for this error. In my case, I have a User, but the name is `first_name`. To solve for this, I simply used:

`alias_attribute :name, :first_name`

on the User.

**Comment by radar** [comment]
Thanks @joelhooks!

**Comment by adamumc** [comment]
Here is a gemfile that reproduces the problem:

```
source 'https://rubygems.org'
gem 'rails', '4.0.2'
gem 'mysql2'
gem 'sass-rails', '~> 4.0.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 1.2'
group :doc do
 gem 'sdoc', require: false
end
gem 'forem', :github => "radar/forem", :branch => "rails4"
gem 'forem-bootstrap', :github => "radar/forem-bootstrap", :branch => "master"
gem 'devise', '~> 3.2.2'
gem 'kaminari', '~> 0.15.1'
gem 'friendly_id', github: "FriendlyId/friendly_id"
gem 'cancan', git: "https://github.com/nukturnal/cancan.git"
```

Still experiencing this issue as of today's state of things.  Using ruby 2.1, but experienced with 2.0 as well.  This occurs even with the to_s method defined and name defined.

I am also getting this warning while bundling:

```
forem at /home/deploy/.rvm/gems/ruby-2.1.0/bundler/gems/forem-de96cc8b9e17 did not have a valid gemspec.
This prevents bundler from installing bins or native extensions, but that may not affect its functionality.
The validation message from Rubygems was:
  duplicate dependency on rails (~> 4.0.0), (= 4.0.0) use:
    add_runtime_dependency 'rails', '~> 4.0.0', '= 4.0.0'
```

I am not very experienced with Ruby yet, but I managed to narrow it down to occurring when forum.rb is not present only.  

Hope this helps find/debug the problem.

**Comment by slavajacobson** [comment]
Same problem....

Here's my gem file

source 'https://rubygems.org'

gem 'rails', '4.0.0'

gem 'sqlite3', group: [:development, :test]
gem 'pg', group: [:production]

gem 'sass-rails', '~> 4.0.0'

gem 'uglifier', '>= 1.3.0'

gem 'coffee-rails', '~> 4.0.0'

gem 'jquery-rails'

gem 'turbolinks'

gem 'jbuilder', '~> 1.2'

group :doc do

  gem 'sdoc', require: false
end

gem 'unicorn'

gem 'capistrano', group: :development

gem 'debugger', group: [:development, :test]
gem 'rvm-capistrano'

gem 'devise'
gem 'foundation-rails'
gem 'figaro'
gem 'whenever', :require => false
gem 'fancybox2-rails', '~> 0.2.4'

group :development, :test do
    gem 'railroady'
end

gem "font-awesome-rails"
gem "jquery-validation-rails"
gem "browser"
gem 'forem', :github => "radar/forem", :branch => "rails4"
gem 'kaminari', '0.15.1'

**Comment by bricker** [comment]
@radar @slavajacobson reproducible app, (long-winded) explanation, and temporary work-around for this error is here: https://github.com/bricker/forem-generator-error . Pull request imminent.

**Comment by slavajacobson** [comment]
@bricker thank you. that worked. except that I also had to do rake db:drop / rake db:migrate berore running forem install
