### ISSUE TITLE
Minor (?) tests failures

### ISSUE THREAD

**Issue by mauriciopasquier** [rubysherpas/forem#524]
I was rebasing some work for #451 and noticed these 2 tests that fail. These
didn't fail when I started working on the feature, so it's something between
commits [a25d11](https://github.com/radar/forem/commit/a25d114fdf5285743330a9c224d503cb2c924f68) and [32627](https://github.com/radar/forem/commit/32627911858b604e8853fb020cd2a38828600d27):

```
Failures:

  1) topics signed in creating a topic is valid with subject and post text
     Failure/Error: assert_seen("forem_user", :within => :post_user)
     Capybara::Ambiguous:
       Ambiguous match, found 2 elements matching css "#posts .post .user"
     # ./spec/support/capybara_ext.rb:16:in `assert_seen'
     # ./spec/features/topics_spec.rb:33:in `block (4 levels) in <top (required)>'

  2) posts posts with deleted users can be viewed
     Failure/Error: visit forum_topic_path(forum, topic)
     ActionView::Template::Error:
       undefined method `model_name' for Forem::NilUser:Class
     # ./app/views/forem/posts/_post.html.erb:33:in `__home_mauricio_dev_yo_forem_app_views_forem_posts__post_html_erb__4377876845587781701_46949280'
     # ./app/views/forem/topics/show.html.erb:44:in `__home_mauricio_dev_yo_forem_app_views_forem_topics_show_html_erb___1669555012106366475_67025540'
     # ./spec/features/posts_spec.rb:19:in `block (3 levels) in <top (required)>'

Finished in 14.84 seconds
220 examples, 2 failures

Failed examples:

rspec ./spec/features/topics_spec.rb:25 # topics signed in creating a topic is valid with subject and post text
rspec ./spec/features/posts_spec.rb:16 # posts posts with deleted users can be viewed

Randomized with seed 14179
```

Failure number 2 didn't fail with every seed, that was weird. Tested with a fresh clone just in case

**Comment by radar** [comment]
These particular tests aren't failing for me on either master or rails4, so I suspect they've been fixed recently. I'm seeing 3 other failures on master, which I will attend to later on.
