### ISSUE TITLE
Error with Forem NilUser instead of deleted user

### ISSUE THREAD

**Issue by hcarver** [rubysherpas/forem#609]
Hey I'm getting an AssociationTypeMismatch error with the Forem::NilUser.
## Reproduction

 1.Create a user, write a post.
 1.Delete the user from the database.
 1.Visit the page with the topic on it.
## Results

Expected result: 
Post displayed as normal with an indication that the user has been deleted.

Actual result: 
ActiveRecord::AssociationTypeMismatch in Forem::TopicsController#show
User expected, got Forem::NilUser
## Versions

```
forem:
  remote: git://github.com/radar/forem.git
  revision: 519f2de9f83a23655745f1ca36a2991dd2251489
  branch: rails4
  specs:
    forem (1.0.0.beta1)

rails (4.1.1)
```
## Stacktrace

```
activerecord (4.1.1) lib/active_record/associations/association.rb:216:in `raise_on_type_mismatch!'
activerecord (4.1.1) lib/active_record/associations/belongs_to_association.rb:12:in `replace'
activerecord (4.1.1) lib/active_record/associations/singular_association.rb:17:in `writer'
activerecord (4.1.1) lib/active_record/associations/builder/association.rb:118:in `forem_user='
.../gems/ruby-2.0.0-p481@bridgeu/bundler/gems/forem-519f2de9f83a/app/models/forem/concerns/nil_user.rb:9:in `user='
.../gems/ruby-2.0.0-p481@bridgeu/bundler/gems/forem-519f2de9f83a/app/models/forem/topic.rb:143:in `set_first_post_user'
activesupport (4.1.1) lib/active_support/callbacks.rb:424:in `block in make_lambda'
activesupport (4.1.1) lib/active_support/callbacks.rb:160:in `call'
activesupport (4.1.1) lib/active_support/callbacks.rb:160:in `block in halting'
activesupport (4.1.1) lib/active_support/callbacks.rb:166:in `call'
activesupport (4.1.1) lib/active_support/callbacks.rb:166:in `block in halting'
activesupport (4.1.1) lib/active_support/callbacks.rb:166:in `call'
activesupport (4.1.1) lib/active_support/callbacks.rb:166:in `block in halting'
activesupport (4.1.1) lib/active_support/callbacks.rb:166:in `call'
activesupport (4.1.1) lib/active_support/callbacks.rb:166:in `block in halting'
activesupport (4.1.1) lib/active_support/callbacks.rb:86:in `call'
activesupport (4.1.1) lib/active_support/callbacks.rb:86:in `run_callbacks'
activerecord (4.1.1) lib/active_record/callbacks.rb:302:in `create_or_update'
activerecord (4.1.1) lib/active_record/persistence.rb:103:in `save'
activerecord (4.1.1) lib/active_record/validations.rb:51:in `save'
activerecord (4.1.1) lib/active_record/attribute_methods/dirty.rb:21:in `save'
activerecord (4.1.1) lib/active_record/transactions.rb:268:in `block (2 levels) in save'
activerecord (4.1.1) lib/active_record/transactions.rb:329:in `block in with_transaction_returning_status'
activerecord (4.1.1) lib/active_record/connection_adapters/abstract/database_statements.rb:211:in `block in transaction'
activerecord (4.1.1) lib/active_record/connection_adapters/abstract/database_statements.rb:219:in `within_new_transaction'
activerecord (4.1.1) lib/active_record/connection_adapters/abstract/database_statements.rb:211:in `transaction'
activerecord (4.1.1) lib/active_record/transactions.rb:208:in `transaction'
activerecord (4.1.1) lib/active_record/transactions.rb:326:in `with_transaction_returning_status'
activerecord (4.1.1) lib/active_record/transactions.rb:268:in `block in save'
activerecord (4.1.1) lib/active_record/transactions.rb:283:in `rollback_active_record_state!'
activerecord (4.1.1) lib/active_record/transactions.rb:267:in `save'
activerecord (4.1.1) lib/active_record/persistence.rb:221:in `update_attribute'
activerecord (4.1.1) lib/active_record/persistence.rb:301:in `increment!'
.../gems/ruby-2.0.0-p481@bridgeu/bundler/gems/forem-519f2de9f83a/app/models/forem/concerns/viewable.rb:21:in `register_view_by'
.../gems/ruby-2.0.0-p481@bridgeu/bundler/gems/forem-519f2de9f83a/app/controllers/forem/topics_controller.rb:121:in `register_view'
.../gems/ruby-2.0.0-p481@bridgeu/bundler/gems/forem-519f2de9f83a/app/controllers/forem/topics_controller.rb:10:in `show'
...
```

**Comment by alexcwatt** [comment]
@hcarver I'm pretty sure #584, which has been merged, should fix this. Please let me know.

**Comment by radar** [comment]
Closing as @alexcwatt says #584 fixed this.
