### ISSUE TITLE
Conflict between Forem and Statesman gems?

### ISSUE THREAD

**Issue by mkuchhal** [rubysherpas/forem#654]
I am working on an RoR-based online classroom product and for handling user - course registrations and progress we use an association 'course_enrollment'. 
We use the Statesman gem for tracking the various states of enrollments.

Rails version is 4.0.0

I installed the forem gem using instructions from the wiki and the forums worked fine, however I could not create new enrollments.

On running this code:

`enrl = @user.course_enrollments.create(course_id: @course.id)`

the error is 

`NoMethodError (undefined method `workflow_spec' for ActiveRecord::Base:Class)`

On removing forem from the app this error was not found.

Any help in solving this will be appreciated.

**Comment by radar** [comment]
Stack trace for the issue please

**Comment by mkuchhal** [comment]
```
activerecord (4.0.0) lib/active_record/dynamic_matchers.rb:22:in `method_missing'
workflow (1.0.0) lib/workflow.rb:243:in `spec'
workflow (1.0.0) lib/workflow.rb:171:in `current_state'
workflow (1.0.0) lib/workflow.rb:363:in `write_initial_state'
activesupport (4.0.0) lib/active_support/callbacks.rb:387:in `_run__837347483__validation__callbacks'
activesupport (4.0.0) lib/active_support/callbacks.rb:80:in `run_callbacks'
activemodel (4.0.0) lib/active_model/validations/callbacks.rb:106:in `run_validations!'
activemodel (4.0.0) lib/active_model/validations.rb:314:in `valid?'
activerecord (4.0.0) lib/active_record/validations.rb:70:in `valid?'
activerecord (4.0.0) lib/active_record/validations.rb:77:in `perform_validations'
activerecord (4.0.0) lib/active_record/validations.rb:51:in `save'
activerecord (4.0.0) lib/active_record/attribute_methods/dirty.rb:32:in `save'
activerecord (4.0.0) lib/active_record/transactions.rb:270:in `block (2 levels) in save'
activerecord (4.0.0) lib/active_record/transactions.rb:326:in `block in with_transaction_returning_status'
activerecord (4.0.0) lib/active_record/connection_adapters/abstract/database_statements.rb:200:in `transaction'
activerecord (4.0.0) lib/active_record/transactions.rb:209:in `transaction'
activerecord (4.0.0) lib/active_record/transactions.rb:323:in `with_transaction_returning_status'
activerecord (4.0.0) lib/active_record/transactions.rb:270:in `block in save'
activerecord (4.0.0) lib/active_record/transactions.rb:281:in `rollback_active_record_state!'
activerecord (4.0.0) lib/active_record/transactions.rb:269:in `save'
activerecord (4.0.0) lib/active_record/associations/has_many_association.rb:39:in `insert_record'
activerecord (4.0.0) lib/active_record/associations/collection_association.rb:463:in `block (2 levels) in create_record'
activerecord (4.0.0) lib/active_record/associations/collection_association.rb:367:in `add_to_target'
activerecord (4.0.0) lib/active_record/associations/collection_association.rb:461:in `block in create_record'
activerecord (4.0.0) lib/active_record/associations/collection_association.rb:152:in `block in transaction'
activerecord (4.0.0) lib/active_record/connection_adapters/abstract/database_statements.rb:202:in `block in transaction'
activerecord (4.0.0) lib/active_record/connection_adapters/abstract/database_statements.rb:210:in `within_new_transaction'
activerecord (4.0.0) lib/active_record/connection_adapters/abstract/database_statements.rb:202:in `transaction'
activerecord (4.0.0) lib/active_record/transactions.rb:209:in `transaction'
activerecord (4.0.0) lib/active_record/associations/collection_association.rb:151:in `transaction'
activerecord (4.0.0) lib/active_record/associations/collection_association.rb:460:in `create_record'
activerecord (4.0.0) lib/active_record/associations/collection_association.rb:121:in `create'
activerecord (4.0.0) lib/active_record/associations/collection_proxy.rb:260:in `create'
app/services/course_enroller.rb:17:in `enroll'
app/controllers/checkout_controller.rb:60:in `block in payment_response'
app/controllers/checkout_controller.rb:59:in `each'
app/controllers/checkout_controller.rb:59:in `payment_response'
actionpack (4.0.0) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
actionpack (4.0.0) lib/abstract_controller/base.rb:189:in `process_action'
actionpack (4.0.0) lib/action_controller/metal/rendering.rb:10:in `process_action'
actionpack (4.0.0) lib/abstract_controller/callbacks.rb:18:in `block in process_action'
activesupport (4.0.0) lib/active_support/callbacks.rb:483:in `_run__475416425__process_action__callbacks'
activesupport (4.0.0) lib/active_support/callbacks.rb:80:in `run_callbacks'
actionpack (4.0.0) lib/abstract_controller/callbacks.rb:17:in `process_action'
actionpack (4.0.0) lib/action_controller/metal/rescue.rb:29:in `process_action'
actionpack (4.0.0) lib/action_controller/metal/instrumentation.rb:31:in `block in process_action'
activesupport (4.0.0) lib/active_support/notifications.rb:159:in `block in instrument'
activesupport (4.0.0) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
activesupport (4.0.0) lib/active_support/notifications.rb:159:in `instrument'
actionpack (4.0.0) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
actionpack (4.0.0) lib/action_controller/metal/params_wrapper.rb:245:in `process_action'
activerecord (4.0.0) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
actionpack (4.0.0) lib/abstract_controller/base.rb:136:in `process'
actionpack (4.0.0) lib/abstract_controller/rendering.rb:44:in `process'
actionpack (4.0.0) lib/action_controller/metal.rb:195:in `dispatch'
actionpack (4.0.0) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
actionpack (4.0.0) lib/action_controller/metal.rb:231:in `block in action'
actionpack (4.0.0) lib/action_dispatch/routing/route_set.rb:80:in `call'
actionpack (4.0.0) lib/action_dispatch/routing/route_set.rb:80:in `dispatch'
actionpack (4.0.0) lib/action_dispatch/routing/route_set.rb:48:in `call'
actionpack (4.0.0) lib/action_dispatch/routing/mapper.rb:44:in `call'
actionpack (4.0.0) lib/action_dispatch/journey/router.rb:71:in `block in call'
actionpack (4.0.0) lib/action_dispatch/journey/router.rb:59:in `each'
actionpack (4.0.0) lib/action_dispatch/journey/router.rb:59:in `call'
actionpack (4.0.0) lib/action_dispatch/routing/route_set.rb:655:in `call'
dragonfly (1.0.5) lib/dragonfly/middleware.rb:14:in `call'
request_store (1.0.5) lib/request_store/middleware.rb:9:in `call'
warden (1.2.3) lib/warden/manager.rb:35:in `block in call'
warden (1.2.3) lib/warden/manager.rb:34:in `catch'
warden (1.2.3) lib/warden/manager.rb:34:in `call'
rack (1.5.2) lib/rack/etag.rb:23:in `call'
rack (1.5.2) lib/rack/conditionalget.rb:35:in `call'
rack (1.5.2) lib/rack/head.rb:11:in `call'
actionpack (4.0.0) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
actionpack (4.0.0) lib/action_dispatch/middleware/flash.rb:241:in `call'
rack (1.5.2) lib/rack/session/abstract/id.rb:225:in `context'
rack (1.5.2) lib/rack/session/abstract/id.rb:220:in `call'
actionpack (4.0.0) lib/action_dispatch/middleware/cookies.rb:486:in `call'
activerecord (4.0.0) lib/active_record/query_cache.rb:36:in `call'
activerecord (4.0.0) lib/active_record/connection_adapters/abstract/connection_pool.rb:626:in `call'
activerecord (4.0.0) lib/active_record/migration.rb:369:in `call'
actionpack (4.0.0) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
activesupport (4.0.0) lib/active_support/callbacks.rb:373:in `_run__197113876__call__callbacks'
activesupport (4.0.0) lib/active_support/callbacks.rb:80:in `run_callbacks'
actionpack (4.0.0) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
actionpack (4.0.0) lib/action_dispatch/middleware/reloader.rb:64:in `call'
actionpack (4.0.0) lib/action_dispatch/middleware/remote_ip.rb:76:in `call'
actionpack (4.0.0) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
actionpack (4.0.0) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
lograge (0.3.0) lib/lograge/rails_ext/rack/logger.rb:15:in `call_app'
railties (4.0.0) lib/rails/rack/logger.rb:21:in `block in call'
activesupport (4.0.0) lib/active_support/tagged_logging.rb:67:in `block in tagged'
activesupport (4.0.0) lib/active_support/tagged_logging.rb:25:in `tagged'
activesupport (4.0.0) lib/active_support/tagged_logging.rb:67:in `tagged'
railties (4.0.0) lib/rails/rack/logger.rb:21:in `call'
actionpack (4.0.0) lib/action_dispatch/middleware/request_id.rb:21:in `call'
rack (1.5.2) lib/rack/methodoverride.rb:21:in `call'
rack (1.5.2) lib/rack/runtime.rb:17:in `call'
dragonfly (1.0.5) lib/dragonfly/cookie_monster.rb:9:in `call'
activesupport (4.0.0) lib/active_support/cache/strategy/local_cache.rb:83:in `call'
rack (1.5.2) lib/rack/lock.rb:17:in `call'
actionpack (4.0.0) lib/action_dispatch/middleware/static.rb:64:in `call'
railties (4.0.0) lib/rails/engine.rb:511:in `call'
railties (4.0.0) lib/rails/application.rb:97:in `call'
rack (1.5.2) lib/rack/content_length.rb:14:in `call'
puma (2.8.1) lib/puma/server.rb:490:in `handle_request'
puma (2.8.1) lib/puma/server.rb:361:in `process_client'
puma (2.8.1) lib/puma/server.rb:254:in `block in run'
puma (2.8.1) lib/puma/thread_pool.rb:92:in `call'
puma (2.8.1) lib/puma/thread_pool.rb:92:in `block in spawn_thread'

```

The above quoted line of code is at line 17 of course_enroller.rb

**Comment by radar** [comment]
Can you provide an app which reproduces this issue?

**Comment by krainboltgreene** [comment]
@mkuchhal Need a reproduction of this to really act.

**Comment by mkuchhal** [comment]
Sorry for the late response. I have stopped working for the firm for which I was using this library. Also we used a different implementation pattern due to which I can no longer reproduce this bug.
